### ISSUE TITLE
"Next instruction" - operator not always concatenates instructions

### ISSUE THREAD

**Issue by DeBourgh** [Rolisteam/DiceParser#100]
Hi,

I am just trying out stuff with the Dice Parser Bot. I noticed a weird behaviour that i did not expected:

The command **!2Lu[cats,dogs,rats,rabbits,bats,squirrels];"asdasd"** was executed as expected with following output: **squirrels,rabbits ; asdasd**. Any string operation seems to work there except an empty string.

However, the command **!2Lu[cats,dogs,rats,rabbits,bats,squirrels];1d4** was not executed as expected with following output: **squirrels,bats**. Any other dice operation after a Lu operation seems not to be executed.

Erik

**Comment by obiwankennedy** [comment]
ok, i will check that.

**Comment by obiwankennedy** [comment]
I checked, it was already fixed on master. I deploy the version on discord.
