### ISSUE TITLE
Regex macro no longer returning result or reply

### ISSUE THREAD

**Issue by hatetank** [Rolisteam/DiceParser#103]
`id: 1 Pattern: ([0-9]+)L([0-9]+) Command: \1d10e10K\2 Regexp: True`

Using <prefix>5L2 or <prefix>5L2;"Roll: $1" would normally produce expected results. Now it just returns nothing at all.  Just stopped working about a week ago.

The following, however, works just fine, as usual.  I do <prefix>d66 and it'll return a result between 11 and 66 (Classic Traveller "percentile" roll)
`id: 2 Pattern: d66 Command: 1d6;1d6;\1 Regexp: True`

Any idea what I might need to do differently now?

**Comment by obiwankennedy** [comment]
For the first command, I strongly recommand to remove the macro and set it again. 
It should work. 
Btw, you can simplify it: 
```
!macro add L d10K False
```
K => e10k


About the second command, I don't get it. Why do you need a \1 in the command but you have no capture in the pattern.
A capture is between parenthesis. (.*) or ([0-9]+).

**Comment by hatetank** [comment]
I didn't need the capture in the second command, that was just probably added prior to me knowing about adding text after a semi-colon if I wanted to add text or a title to the roll on the fly

Thanks for the help. I swear I looked for something like K and just never found it.  Still confused why it worked, then didn't, though.
