### ISSUE TITLE
Macros broken

### ISSUE THREAD

**Issue by LiefAmai** [Rolisteam/DiceParser#104]
Macros no longer appear to be working?

![Screenshot_1](https://user-images.githubusercontent.com/52230892/97096827-8f6d7c80-163f-11eb-9523-851bef144e59.png)

**Comment by obiwankennedy** [comment]
Remove them and adding them should fix the issue.

**Comment by LiefAmai** [comment]
Figured that out after posting this. It's kind of frustrating that they're suddenly all broken, though- yet the bot still knows they exist.

**Comment by TripleOakLeaf** [comment]
I have to remove and re-add them fairly often. They break at the worst times.

**Comment by clameire** [comment]
When i use only one macro A, this stand alone macro A works fine. When iuse only one macro B, this stand alone macro B works fine too. But if i add both A and B macros, then B macros works and A does nothing. How is it possible ? If i remove B, then A starts working again...

**Comment by obiwankennedy** [comment]
@clameire  yes it is possible if the pattern of A and B are conflicting to each other.

**Comment by clameire** [comment]
Different macros aren't totally independent? Why? How? Those are five macros with different id/names that use Xd10, and display different text based on the number of each pair (1-2,3-4,5-6...) I really can't see hhow they could interfere with each others... What can we do or can't we do? Where to find proper extensive documentation on that?

**Comment by clameire** [comment]
Example of what i'm trying to do... 
[macros.txt](https://github.com/Rolisteam/DiceParser/files/5471524/macros.txt)

**Comment by clameire** [comment]
Nevermind, seems like it was linked to invisible differences of encoding of wuxia (chinese elemental) characters i wasn't aware of... Sorry for the disturbance

**Comment by obiwankennedy** [comment]
no update since 3 months, I closed this ticket.
