### ISSUE TITLE
Does not sort multiple dice rolls with "keeping highest" logic?

### ISSUE THREAD

**Issue by kakardo** [Rolisteam/DiceParser#107]
This is the string I'm using:
!4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;4d6k3

What I wish to do is to sort the final array generated from the roll.

I'm going to use d1000:s for clearer differences in value:
!4d1000k3;4d1000k3;4d1000k3;4d1000k3;4d1000k3;4d1000k3

So I have tried a couple of things:

Adding "s" after the last d1000:
!4d1000k3;4d1000k3;4d1000k3;4d1000k3;4d1000k3;4d1000sk3

Adding "s" after every d1000:
!4d1000sk3;4d1000sk3;4d1000sk3;4d1000sk3;4d1000sk3;4d1000sk3

Is this is a bug or am I simply using this wrong? Thanks in advance! Great stuff btw!

**Comment by obiwankennedy** [comment]
Yes, you are doing it in a wrong way.

The operator k is already sorting things. So, 4d100sk3 and 4d100k3 will give the same result.
Here, you want to sort result from several instructions.
So you have to play with operators that can deal with that.

# Merge operator
The merge operator takes all instruction and merge then into one.
So operator after the merge are dealing with result from every instructions.

I take a simpler example but the idea is the same:

Let say I want to sort the result of this command: `2d10;2d100`

First instruction is: 2d10
Second instruction is: 2d100

If I add a sort operator after 2d100 (like this: `2d10;2d100s`)
The s will only sort the result from 2d100. Instructions are worlds apart. 

Not I try to merge them: with the **m** operator.
`2d10;2d100ms` works.
The merge operator bring together the first instruction world into the second instruction world. It is destructive. Merge change completely stored data inside the bot. 

# Bind operator

Bind operator has the same result than Merge but it is not destructive. 
`!2d10;2d100b;$2s;"Sorted: [@3]"`
In the second instruction, I bound result from previous one, so in the third instruction I can sort the result and then I display the rest. As I don't change the data. At the end, the bot still have several instructions to show result. It is why I managed the output.

**Comment by kakardo** [comment]
Wow thanks for the answer! Sadly I'm still having problems. Problem with merge is that it merges the rolls together, and bind is giving me outputs that should not be possible (too high).

What I want to do is to roll 4d6 and sum up the 3 highest results. I want to do this 6 times.
This should give me six result with a value between 3-18.
ResultArray = [a, b, c, d, e, f]

And I wish to be able to sort the array. Any ideas?

**Comment by kakardo** [comment]
Pretty please...?

**Comment by obiwankennedy** [comment]
I'm working on it.

**Comment by obiwankennedy** [comment]
```
!4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;[$1,$2,$3,$4,$5,$6]k1;[$1,$2,$3,$4,$5,$6]k2kl1;[$1,$2,$3,$4,$5,$6]k3kl1;[$1,$2,$3,$4,$5,$6]k4kl1;[$1,$2,$3,$4,$5,$6]k5kl1;[$1,$2,$3,$4,$5,$6]kl1;"Score: [$7,$8,$9,$10,$11,$12]"
```
Do what you want.
I will try to improve some mechanism in diceparser to help getting same result with a shorter command.

**Comment by kakardo** [comment]
It works perfectly! :D Thank you so much!
Is there a way to add up the scores at the end?

!4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;[$1,$2,$3,$4,$5,$6]k1;[$1,$2,$3,$4,$5,$6]k2kl1;[$1,$2,$3,$4,$5,$6]k3kl1;[$1,$2,$3,$4,$5,$6]k4kl1;[$1,$2,$3,$4,$5,$6]k5kl1;[$1,$2,$3,$4,$5,$6]kl1;"Ability Score: [$7,$8,$9,$10,$11,$12], Total:[$1+$2+$3+$4+$5+$6]"

I wrote this but it doesn't add them together.

**Comment by obiwankennedy** [comment]
Yes, because `Total:[$1+$2+$3+$4+$5+$6]"` is inside the output instruction.
You have to put it in a regular instruction.

```
!4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;[$1,$2,$3,$4,$5,$6]k1;[$1,$2,$3,$4,$5,$6]k2kl1;[$1,$2,$3,$4,$5,$6]k3kl1;[$1,$2,$3,$4,$5,$6]k4kl1;[$1,$2,$3,$4,$5,$6]k5kl1;[$1,$2,$3,$4,$5,$6]kl1;$1+$2+$3+$4+$5+$6;"Ability Score: [$7,$8,$9,$10,$11,$12], Total:[$13]"
```

BTW, are you sure you want to sum result of the dice roll ? You may want to sum result after the keep operator, NO ? 
To do so, just replace `$1+$2+$3+$4+$5+$6` to `$7+$8+$9+$10+$11+$12` in the previous command.

**Comment by kakardo** [comment]
Oh now it does what I tried to do. Thank you again! :D

> BTW, are you sure you want to sum result of the dice roll ? You may want to sum result after the keep operator, NO ?
To do so, just replace `$1+$2+$3+$4+$5+$6` to `$7+$8+$9+$10+$11+$12` in the previous command.

Is the only difference that the first option (`$1+$2+$3+$4+$5+$6`) sums the rolls before the sorting? I'm happy as long as it shows a point total of what has been rolled.
