### ISSUE TITLE
Allow the Discord bot's prefix to be a mention

### ISSUE THREAD

**Issue by birdperson-lives** [Rolisteam/DiceParser#108]
Currently, trying to set the bot's prefix to mentioning it (via `!prefix set "@DiceParser "`) leaves the bot in a broken state where it does not recognize any commands, at least AFAICT. It would be useful to be able to set the bot's prefix to its mention, as mention-to-invoke is easy to remember and virtually guaranteed not to conflict with any other bot.

Any resolution to this issue would ideally work even if the bot had a nickname in the server. It would be nice if the mention could be embedded in an arbitrary prefix string, but I think most users would be fine if the only supported mention prefix was `"@DiceParser "`.

**Comment by obiwankennedy** [comment]
Done
