### ISSUE TITLE
Issues with Aliases.

### ISSUE THREAD

**Issue by WesHappenin** [Rolisteam/DiceParser#110]
I have trying to simply make Aliases following the directions given by !alias and the repository. But the command to use the alias is not working, I've tried it several ways to be sure, removed and remade the aliases several times. 

I feel it's a bug, but I'd be even happier if I'm just doing something silly.

![Screenshot_20210117-093704_Discord](https://user-images.githubusercontent.com/77578769/104846611-69a3ec80-58a9-11eb-91ea-e93f3c3935d8.jpg)
![Screenshot_20210117-094717_Discord](https://user-images.githubusercontent.com/77578769/104846612-6a3c8300-58a9-11eb-999d-1fbf1b4f016d.jpg)

**Comment by obiwankennedy** [comment]
No need to repeat the ! inside the commands part. 
See my example: 
![image](https://user-images.githubusercontent.com/69177/107083593-2973c200-67f6-11eb-9d22-b9a22ab4f0d4.png)
