### ISSUE TITLE
Show result as plain text - Not working

### ISSUE THREAD

**Issue by TiliSleepStealer** [Rolisteam/DiceParser#111]
![image](https://user-images.githubusercontent.com/6567869/106533102-6a639200-64e9-11eb-94f3-6f683aee1da4.png)

When I type !&1d6 in discord the output is still in a box.

**Comment by obiwankennedy** [comment]
As you can see on the image, I fix the issue on the dev bot. I will deploy the solution soon. Tomorrow or this week-end.

![image](https://user-images.githubusercontent.com/69177/106982275-10223580-6764-11eb-969a-c0fb213e23d9.png)

**Comment by obiwankennedy** [comment]
Just deploy new version of diceparser.

You can configure the output from the command conf.
more details: `!help conf`
