### ISSUE TITLE
Discord - Roll at Different Channel

### ISSUE THREAD

**Issue by ValeTheVioletMote** [Rolisteam/DiceParser#116]
Allow some means of rolling that directs the bot to dump the output in a directed channel (likely by the user providing the channel id). 

I'd like to be able to write up a complex roll with logic and have it output to a different channel. If I want to hide, for example, that my player needed a 14, and as such simply output the string result of the roll.

Potential issue: a malicious user takes advantage of the bot's permissions and dumps a roll into a channel that the bot can write to, but the user cannot.

**Comment by obiwankennedy** [comment]
I just deploy a new version of the bot with a feature to do so.

`=>#Channelname !1d6`

Above command displays the result of 1d6 into #Channelname.

screen shots:
command:
![image](https://user-images.githubusercontent.com/69177/113502331-06326e00-952c-11eb-86e0-0c4e71ba4bac.png)

result:
![image](https://user-images.githubusercontent.com/69177/113502349-2f52fe80-952c-11eb-8764-1c1a36a498ce.png)

**Comment by ValeTheVioletMote** [comment]
Awesome!!! Thank you so much!
