### ISSUE TITLE
Macros not working/returning any output

### ISSUE THREAD

**Issue by meffcio** [Rolisteam/DiceParser#120]
I'm preparing some macros for a game of [Lasers & Feelings](http://onesevendesign.com/lasers_and_feelings_rpg.pdf). I've come up with the commands that give me the desired results, for example for a 2 die roll of LASERS with the character's number being 4:
`!2d6;$1c[<=4];$1i.[=4]{"Successes: $2 (Laser Feelings!) [Rolls: %2]"}{"Successes: $2 [Rolls: %2]"}`
where 
`!2d6` - just roll two 6-faced die
`$1c[<=4]` - count how many dice rolled under the character's number - that's the number of successes
`$1i.[=4]{"Successes: $2 (Laser Feelings!) [Rolls: %2]"}{"Successes: $2 [Rolls: %2]"}` - check if any die rolled exactly the character's number - if so, then print an information that he got "laser feelings" along with the number of successes and the actual die results. If not, then only print the how many die succeded, along with the die results.

The command itself works as intended.
![image](https://user-images.githubusercontent.com/9597352/110782938-09597780-8268-11eb-82f9-75583f975d44.png)
However, when I try to put the command into a macro
`!macro add ([0-9]+)L([0-9]+) "!\1d6;$1c[<=\2];$1i.[=\2]{\"Successes: $2 (Laser Feelings!) [Rolls: %2]\"}{\"Successes: $2 [Rolls: %2]\"}" True`
it is indeed saved, but calling the macro does not yield any results.
![image](https://user-images.githubusercontent.com/9597352/110783280-82f16580-8268-11eb-969e-746aef424b60.png)

**Comment by obiwankennedy** [comment]
No need to start you macro code with `!`.

```
!macro add ([0-9]+)L([0-9]+) "\1d6;$1c[<=\2];$1i.[=\2]{\"Successes: $2 (Laser Feelings!) [Rolls: %2]\"}{\"Successes: $2 [Rolls: %2]\"}" True
``` 
And you should be ok.

**Comment by meffcio** [comment]
How did I miss this... 🤦‍♂️ I'm pretty sure I've tried it without the exclamation mark alread, but apparently I didn't...
![image](https://user-images.githubusercontent.com/9597352/110786464-75d67580-826c-11eb-9c0b-de585c1b66e5.png)
Works as intented, forget I even asked XD
