### ISSUE TITLE
New Feature: Discord: Repeat name of user who rolled in the roll results

### ISSUE THREAD

**Issue by tkurtbond** [Rolisteam/DiceParser#121]
When several players are all rolling dice in Discord using DiceParser, the results of their rolls are intermixed without any indication of which of the players made what roll.  So you can see, for instance, two users issuing a dice command at the same time and then their results without any indicate of which one made what, and if they are both rolling 3d6, for instance, there is no way to determine which is which.

**Comment by obiwankennedy** [comment]
dupplicate of #106
