### ISSUE TITLE
How can I use DiceParser on irc channel?

### ISSUE THREAD

**Issue by STASWIT** [Rolisteam/DiceParser#122]
I want to use this program on my irc server, but I couldn't found any document about it.

**Comment by obiwankennedy** [comment]
Hi, I did not try the irc support for a while. 
Basically, you have to build the folder IRC and set details about your server. It will connect to irc as a regular user  and respond to call !

**Comment by STASWIT** [comment]
![image](https://user-images.githubusercontent.com/32238678/112739399-c822d080-8fa6-11eb-825f-c262ac0bde28.png)
When I build the IRC folder using cmake and make, it pushed some errors.

**Comment by obiwankennedy** [comment]
I just commit/push a new version where it works again and I added a readme file.

**Comment by obiwankennedy** [comment]
IRC support has been dropped.
