### ISSUE TITLE
@here mention causes error in DiceParser bot for Discord

### ISSUE THREAD

**Issue by kzalewski11** [Rolisteam/DiceParser#124]
Notifying all non-idle users (@here) in a Discord server with DiceParser causes the bot to throw "Error:  The @ operator expects dice result. Please check the documentation to fix your command."

This issue does not appear to be present when using the @everyone mention to notify all users regardless of online presence, mentioning other users by name with @\<name\>, or when user enters @ followed by other words that are not bound to a mention type.

**Comment by obiwankennedy** [comment]
Yes, it is a little bug from the API I use to identify the mention. As the bot can be triggered if you mention him at the beginning of the message.

I fix it already and i will push that change this week-end.
