### ISSUE TITLE
next instruction doesn't work with multiple dice rolls and explode

### ISSUE THREAD

**Issue by Xsilleze** [Rolisteam/DiceParser#125]
What I want to roll: !4d6Kl;4d6Kl;4d6Kl;4d6Kl;4d6Kl;4d6Kl

Its suppose to roll 4d6 6 times and destroy the lowest number of each roll separately but the Kl function doesn't work after a " ; " next instruction 

am I doing something wrong?

**Comment by obiwankennedy** [comment]
The command you want to roll is `!4d6K3;4d6K3;4d6K3;4d6K3;4d6K3;4d6K3`

**Comment by Xsilleze** [comment]
![dice parser](https://user-images.githubusercontent.com/82823461/115272460-c69d9000-a181-11eb-9fcb-bbc16ef3c41a.PNG)

I tried this command but some random number pop ups and is added to the equation but not everytime.
As you can see within this brackets [ ] a random number appears and is added to the roll and I'm not sure with that 8

The result is 14 so 6 + 2 + 3 + 3 + 2 = 16 - lowest number which is 2 =  14.

**Comment by WanderSiqueira** [comment]
Kl is about keeping the lowest.
K is about Keeping and Exploding (not what you want)

Run this command: !4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;4d6k3

k is the command to keep.
