### ISSUE TITLE
A single macro is simple not working

### ISSUE THREAD

**Issue by WanderSiqueira** [Rolisteam/DiceParser#126]
I'm having a problem here with this one single macro that just don't work. There's any error in the macro? Can someone help me? I've already tried to change the regular expression, changing the macro name and the order of the dice throws. I'm not exactly good at programming and stuff, so I don't know if I commited a mistake or if it is a bug.

![image](https://user-images.githubusercontent.com/80720153/115938488-3d33d980-a471-11eb-9d4b-c9a7172b35cf.png)

**Comment by obiwankennedy** [comment]
The order is bad: 
When you set your macro, afcc should be set before af. 
because af will match and afcc will not be tested.

**Comment by WanderSiqueira** [comment]
It worked. Thank you!
