### ISSUE TITLE
Macros expanding in comments

### ISSUE THREAD

**Issue by futuraprime** [Rolisteam/DiceParser#127]
I've created a macro for Ars Magica stress dice, which I assigned the label `s`—but this gets caught in comments, like so:

```
Player:
!1d10+7 # Vis

DiceParser BOT:
Vid10e1y;$1k1;$1c1;$22**$3;$1i[=10]{"botched (%2)"}{"rolled %3 (%2)"}
# 10
Details:[1d10+7 #  (3)]
```

(The 's' in Vis has been converted into the command macro)

**Comment by obiwankennedy** [comment]
It is not a bug, you have to specify a less permissive pattern to not trigger the macro.

**Comment by obiwankennedy** [comment]
See #142 for explanation
