### ISSUE TITLE
Continuously Explode Without Adding, Count Results After All Explosions?

### ISSUE THREAD

**Issue by randypinion** [Rolisteam/DiceParser#128]
I may just be very bad at understanding the commands in the readme file, but I've been experimenting with things and not having luck at all.

I am working with a d6 dice system where Successes are counted (each result of 4, 5, or 6 counts as 1 Success) and where the highest result explodes (each roll of a 6 rolls a new die; if the new die also rolls a 6, it _also_ rolls again, etc.). In this case (explosions), the results are _not_ added together; each explosion die result is checked against the Success condition separately.

So, for instance, if you rolled 5d6, and the initial rolls were:

[3, 4, 2, 1, 6, 5]

the single 6 in the original pool would be re-rolled:

[6]

lucky! 6 again; re-roll again:

[1]

Aww, okay. _Now_, count all results of 4 or higher from the total pool of results:

[3, **4**, 2, 1, **6**, **5**, **6**, 1]

Successes: 4

How would I go about doing this in DiceParser/Rolisteam?

**Comment by obiwankennedy** [comment]
```
!4d3;$1k1;$1c[>=4];$3i:[>0]{$1e$2}{$1};$4c[>=4];"score: $5 [@4] initial roll:[@1]"
```

Does that make the job ?

**Comment by randypinion** [comment]
Well, had to change it to d6 rather than 3, but even then, it is exploding 5s, not just 6s. Hmm.

**Comment by obiwankennedy** [comment]
Because 5 is the highest result.
You said: `where the highest result explodes` it is why I computed the highest result and the result of this computation is part of the condition to count successes.

**Comment by randypinion** [comment]
Sorry, that was bad wording on my part. I mean to say, "Explode any and all 6s" (the highest result you can get on a d6). Continually exploding if the 6 rolls another 6. And then tally up >=4 after that.
