### ISSUE TITLE
Diceparser not working

### ISSUE THREAD

**Issue by raconteurtt** [Rolisteam/DiceParser#129]
I'm very confused at the moment. The bot is working in two other servers I run, but not the third. I've tried kicking and reinviting it and changing the permissions but nothing is working.

**Comment by obiwankennedy** [comment]
Does diceparser appear offline ? on the server where it does not work ?

**Comment by raconteurtt** [comment]
It’s idle but working in other servers. It’s in our giveaway channel where
it has administrator permissions

**Comment by obiwankennedy** [comment]
Is it fixed ? I reboot the bot and increase its capacity. It may reach its limit.

**Comment by raconteurtt** [comment]
It’s not working yet unfortunately

**Comment by obiwankennedy** [comment]
Could you join https://discord.com/invite/MrMrQwX ? and send me a MP with an invitation to your server. I will check what wrong tonight (in few ours)
