### ISSUE TITLE
Strange `-` behavior in macro

### ISSUE THREAD

**Issue by tim-elmer** [Rolisteam/DiceParser#131]
Trying to add a macro to the Discord bot, encountering unexpected response.

I'm attempting to add the macro `Pattern: -d([0-9]+) Command: 2d\1kl1 Regexp: True`, with the intent of making DnD 5e advantage/disadvantage rolls a bit easier to remember. This works fine with `Pattern: \+d([0-9]+) Command: 2d\1k1 Regexp: True` (`+dX` e.g. `+d20`), but using `-dX` (e.g. `-d20`) results in the bot returning an image: 
![image](https://user-images.githubusercontent.com/12878113/127079782-4386444d-fef8-41fb-b621-95f3b14c0a46.png)

Perhaps this is a collision with the arithmetic operators? I changed the `-` in the pattern to `\.` and that works just fine.

**Comment by wilcoxon** [comment]
There definitely seems to be something in DiceParser with -d (not sure if it is the minus, the d, the combination, or what).  I tried creating a macro sym-d([0-9]+) and that failed but changing it to symd or sym-x worked fine (just not sym-d).

**Comment by obiwankennedy** [comment]
I strongly recommend to set -1dX instead of -dX.

**Comment by tim-elmer** [comment]
That's fine, as I've found a workaround, but any characters (or sequences of characters) that cannot be used in a macro should be documented.
