### ISSUE TITLE
DiceParser no longer detecting dice commands from another bot

### ISSUE THREAD

**Issue by XanIves** [Rolisteam/DiceParser#132]
DiceParser doesn't seem to be listening to bot messages. I am able to call DiceParser with a command with my client user, but the same command+same channel+same server but using my bot user returns no output from DiceParser.

Does DiceParser no longer listen to other discord bots?

Example below:
![image](https://user-images.githubusercontent.com/38440635/128287271-846e73e6-6258-4441-9247-f40db1cf1523.png)

**Comment by obiwankennedy** [comment]
There is a conf parameter now to allow diceparser to answer to other bots.

this command `!conf set answerbot on` should fix your issue.

**Comment by XanIves** [comment]
Thanks for the quick response! I'll try that out and see if it works 👉😎👉

**Comment by XanIves** [comment]
Worked like a charm, closing this issue!
