### ISSUE TITLE
DiceParser on Discord doesn't support Threads

### ISSUE THREAD

**Issue by itaisanders** [Rolisteam/DiceParser#137]
I've been using DiceParser on my Discord server for a couple of years.
It works great in channels, but it doesn't seem to be able to react to messages in Threads.
I double-checked permissions and I found at least one other bot that manages to do this (Avrae).

It would be awesome if you could support this. Thanks.

**Comment by pirateprincess23** [comment]
Came here to report the same issue.

**Comment by Juustar** [comment]
Really a shame they haven't updated with support for Threads yet. For now I'll have to use Avrae, even though DiceParser has more useful features, simply because I use Threads for organization and need the ability to roll within them.

**Comment by obiwankennedy** [comment]
The thread support is done, but not deployed yet.

**Comment by lafber** [comment]
Any know date for the deployment of the thread support?

**Comment by obiwankennedy** [comment]
The thread support is available now.
