### ISSUE TITLE
Way to roll dice after critical success or failure?

### ISSUE THREAD

**Issue by willartj** [Rolisteam/DiceParser#138]
This works, but is there a way of having cideparser automatically roll 3d6 if critical success or critical failure?

!3d6i:[<4]{"Critical Fail %1 [%2]"}{i:[>18]{"Critical Success %1 [%2]"}{"Standard %1 [%2]"}}

**Comment by obiwankennedy** [comment]
The easiest way to do that is to roll 3d6 every time and only display the value on critical success and to hide the value in any other cases.
