### ISSUE TITLE
Exploding Doubles

### ISSUE THREAD

**Issue by Ivokros** [Rolisteam/DiceParser#143]
Hello folks,

If someone knows how to write a command that rolls 2d6 and whenever there are doubles it rerolls another 2d6 and adds the result repeatedly until there are no doubles it would be great to know how. I tried for a while and could not figure it out. Eg I roll 1,4 it does nothing but 3,3 rolls again and gets 4,4 then 5,4 I would get a combined result of 23.

Thanks to anyone who can help!

**Comment by PXL-C** [comment]
The command to do this is `!2d6t`
