### ISSUE TITLE
Bot stopped working with Discord's latest version

### ISSUE THREAD

**Issue by GTechene** [Rolisteam/DiceParser#146]
Hello,
The commands used to work great before yesterday. Now, nothing seems to trigger a reaction from the bot. Also, a direct message provokes an error :
![image](https://user-images.githubusercontent.com/17823219/188096964-53d7eda9-2111-45ad-81f9-67bd3503516c.png)

Re-inviting the bot shows this error :
![image](https://user-images.githubusercontent.com/17823219/188096618-a9d8d07f-dd20-4692-9b00-4b4fd6f2159a.png)

(sorry for the French display ; basically, it says the bot cannot join because it was not verified and that we should ask the developer about verification at https://dis.gd/bot-verification )

Any idea what's going on ?

**Comment by JacobBorgmann** [comment]
I have discovered this as well It was working until very recently
I see that DiceParser is a verified bot, and I tried a few different commands, I couldn't even get /Help to work

![diceparsererror](https://user-images.githubusercontent.com/112707041/188154227-b2e826f2-d1d2-4ab6-aaee-053b2dfb5d40.png)

![verifiedbot](https://user-images.githubusercontent.com/112707041/188154442-184d36d9-6ea6-414a-b05e-35610dd93cd0.png)

**Comment by god-of-ghz** [comment]
Yea it's completely borked rn. Doesn't respond to any kind of command, at all
![image](https://user-images.githubusercontent.com/107101939/188275766-1a410023-cc6d-45af-9c68-baca26fd590a.png)

**Comment by StarSword-C** [comment]
Discord apparently decided to completely rework how bots work with the most recent patches. https://discord.com/developers/docs/change-log#sep-1-2022

**Comment by WladySpb** [comment]
also have this problem in one of my servers, but correct work on ahother discord servers...

**Comment by obiwankennedy** [comment]
I just deployed the new version which allows slash commands.
Try it, if it does not work on your server. It probably means that the bot has not the proper permissions.
Kick it and re-invite in your server with this link: 

https://discord.com/api/oauth2/authorize?client_id=279722369260453888&permissions=277025429504&scope=applications.commands%20bot

**Comment by GTechene** [comment]
Thanks a lot, it works fine now after re-invite !
The aliases do not work anymore but I suppose that's expected. Need to type "/roll", click on the command that appears, and enter the command as usual without the ! alias.

![image](https://user-images.githubusercontent.com/17823219/188310638-bc6c9052-d623-4548-a8fe-6fd79e7db8f6.png)

![image](https://user-images.githubusercontent.com/17823219/188310645-a6cf9495-c4ea-44fc-8158-ff51c256e9e5.png)

I still can't make it work in DM (still get the "The application did not respond" error) but that's not really an issue for me.

Thanks again.
