### ISSUE TITLE
Prefix not working

### ISSUE THREAD

**Issue by werff** [Rolisteam/DiceParser#147]
If I try to use the prefix (that is the base one, "!") the bot doesn't respond.
I need to use the /roll command to do the rolls.

https://cdn.discordapp.com/attachments/815593343303024640/1016096734100852776/unknown.png

**Comment by obiwankennedy** [comment]
It is due to a change of discord. They forces bot in use in more than 100 servers to use slash commands
https://support-dev.discord.com/hc/en-us/articles/4404772028055

**Comment by werff** [comment]
Then will this plugin ask for the "PRIVILEGED INTENT"?

Because we use it for it's ease and fast response, using everything with /roll d6 it's quite longer and the users that play using phone have been having problems (that, as always, can be fixed with more practice in the worst case), just to know and tell something to the users on my discord.
Sorry if i'm being bothersome, it's not my intention and I'm gratefull for your work in this plugin, I just want to know something to tell my group and calm them a bit. Thanks for everything and, whatever is the answer, I'm gratefull for this great plugin.

**Comment by obiwankennedy** [comment]
I will ask for this privileged intent but there is almost no chance they allow diceparser to have it. 
Meanwhile we are stuck to /roll function. I will probably rename /r in order to make it shorter.
