### ISSUE TITLE
bot does not allow users below the rank of admin to roll

### ISSUE THREAD

**Issue by restedwaves** [Rolisteam/DiceParser#156]
not sure if there is an unlisted config i could mess with to fix it or if i just couldn't find it in the current outdated documentation but its a severe issue

**Comment by kurali1215** [comment]
I am having the same issue and it is making it difficult for people in the RP server I'm in to roll for themselves.

**Comment by obiwankennedy** [comment]
It is just a permission issue. 
You have to fix permission on the server level and Channel as well.

I can't help you. It is on your side

**Comment by restedwaves** [comment]
wasn't an issue with bot perms from our testing but with how old this report is i'll assume it was fixed somehow
