### ISSUE TITLE
Discord Compatibilty

### ISSUE THREAD

**Issue by Jikosh** [Rolisteam/DiceParser#16]
Far as i can tell, the only thing that actually works for discord involving this is... rolling many dice at once.

Everything else, arithmetic, your various code modifiers, all of it seems broken and incapable of doing anything, even gave the bot full admin access, nothing.

**Comment by obiwankennedy** [comment]
I don't have context here but. It works I just tested:


> !1d10
# 6
Details:[1d10 (6)]

> !10d10e10k4
# 40
Details:[10d10e10k4 (16 [10,6] 8 8 8 6 5 5 4 2 1)]
16 + 8 + 8 + 8 = 40

> !10+10+4
# 24
Details:[10+10+4 ()]

**Comment by obiwankennedy** [comment]
I invite you to join https://discordapp.com/invite/MrMrQwX  then I will be able to help.  We have testing and support channels.

**Comment by Jikosh** [comment]
It seems there was something wrong on my end, not with the bot itself, my apologies!
