### ISSUE TITLE
Ambiguous licensing

### ISSUE THREAD

**Issue by Kodiologist** [Rolisteam/DiceParser#160]
`COPYING.txt` has a copy of the GPL 2. `LICENSE` has a copy of the GPL 3. The README doesn't mention licensing at all. What's intended here? A disjunction of GPLs 2 and 3?

**Comment by obiwankennedy** [comment]
It is an error. 
The license of this code is GPLv3 (The `LICENSE` file is older that COPYING.txt )
I should remove the GPLv2 text, it was inserted by mistake.
