### ISSUE TITLE
Possible bug: wrong macro called/rolled

### ISSUE THREAD

**Issue by Attronarch** [Rolisteam/DiceParser#162]
Add following macros:

`cc-method-i 4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;4d6k3;[$1,$2,$3,$4,$5,$6]s;"Character abilities\nMethod I\n\n@7\n" False`

`cc-method-ii 3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;[$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12]k6;"Character abilities\nMethod II\n\n@13\n" False`

`cc-method-iii 3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;[$1, $2, $3, $4, $5, $6]k1;[$7, $8, $9, $10, $11, $12]k1;[$13, $14, $15, $16, $17, $18]k1;[$19, $20, $21, $22, $23, $24]k1;[$25, $26, $27, $28, $29, $30]k1;[$31, $32, $33, $34, $35, $36]k1;"Character abilities\nMethod III\n\nSTR: @37\nINT: @38\nWIS: @39\nDEX: @40\nCON: @41\nCHA: @42\n" False`

`cc-method-iv 3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;3d6;"Character abilities\nMethod IV\n\nSET  1\n\nSTR: $1\nINT: $2\nWIS: $3\nDEX: $4\nCON: $5\nCHA: $6\n\nSET  2\n\nSTR: $7\nINT: $8\nWIS: $9\nDEX: $10\nCON: $11\nCHA: $12\n\nSET  3\n\nSTR: $13\nINT: $14\nWIS: $15\nDEX: $16\nCON: $17\nCHA: $18\n\nSET  4\n\nSTR: $19\nINT: $20\nWIS: $21\nDEX: $22\nCON: $23\nCHA: $24\n\nSET  5\n\nSTR: $25\nINT: $26\nWIS: $27\nDEX: $28\nCON: $29\nCHA: $30\n\nSET  6\n\nSTR: $31\nINT: $32\nWIS: $33\nDEX: $34\nCON: $35\nCHA: $36\n\nSET  7\n\nSTR: $37\nINT: $38\nWIS: $39\nDEX: $40\nCON: $41\nCHA: $42\n\nSET  8\n\nSTR: $43\nINT: $44\nWIS: $45\nDEX: $46\nCON: $47\nCHA: $48\n\nSET  9\n\nSTR: $49\nINT: $50\nWIS: $51\nDEX: $52\nCON: $53\nCHA: $54\n\nSET  10\n\nSTR: $55\nINT: $56\nWIS: $57\nDEX: $58\nCON: $59\nCHA: $60\n\nSET  11\n\nSTR: $61\nINT: $62\nWIS: $63\nDEX: $64\nCON: $65\nCHA: $66\n\nSET  12\n\nSTR: $67\nINT: $68\nWIS: $69\nDEX: $70\nCON: $71\nCHA: $72\n" False`

Rolling **cc-method-ii** and **cc-method-iii** will always result with rolling **cc-method-i** instead.

Rolling **cc-method-iv** will produce the expected result.

**Comment by obiwankennedy** [comment]
The order when settings macro is important. 
So if you set cc-method-i  before cc-method-iii it will always find cc-method-i into cc-method-iii
