### ISSUE TITLE
Discord: "playing" message?

### ISSUE THREAD

**Issue by Sandvich** [Rolisteam/DiceParser#17]
Hi,
A relatively small request, I hope, but it'd be great if we could set a "playing" message when using DiceParser on Discord. It's not really important, but it'd be cool to have :)

**Comment by obiwankennedy** [comment]
Ok, I will take a look at it.

**Comment by obiwankennedy** [comment]
Ok set the status is easy but it will be visible on all discord servers using DiceParser; not only your server.
