### ISSUE TITLE
On Discord, macro command does  nothing

### ISSUE THREAD

**Issue by aterastrum** [Rolisteam/DiceParser#19]
When using the !macro command and !macro list does nothing. Diceparser does not even give me an error in response. 
![macro bug](https://user-images.githubusercontent.com/45020337/48451331-fd347c80-e777-11e8-8539-33c8ed7fe747.png)

**Comment by obiwankennedy** [comment]
You may have fallen into a strange bug:

when you never set any macro then you change the prefix, and then set any macro does not work.

I think a reboot of the bot may fix the issue but i would like to make some tests.
if you can invite me to your server for test purpose, it will be great.

**Comment by aterastrum** [comment]
https://discord.gg/DgcAVma

**Comment by aterastrum** [comment]
The bug was occuring before i changed the prefix as well. I changed the prefix initially to see if i could get !macro to work with a different prefix.

**Comment by aterastrum** [comment]
Quick question, i couldnt message you on discord. But i cant get a nested IF function to work. Is this not supported? if not ill just find a workaround. Thanks for all youve done! its amazing!
