### ISSUE TITLE
Bugs with multi-term expressions

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Rolisteam/DiceParser#22]
When I roll an expression that has more than one kind of dice in it, the result doesn't clearly specify which type of dice is which:

```
$ dice 'd6+d8'
Result: 9 - details:[d6+d8 (d:(3) - d:(6))]
```

It looks like the `d:` terms are supposed to have a number after "d", and looking in `DisplayToolBox::diceToText()`, there seems to be code to interpolate the face numbers, so I'm not sure why they aren't showing.

In addition, it seems that multi-term expressions are not consistently evaluated correctly. For instance:

```
$ dice 'd4+d6+d8+d10+d12'
Result: 4 - details:[d4+d6+d8+d10+d12 (d:(2) - d:(2))]
$ dice '((3+4)*2)d6'
Result: 7 - details:[((3+4)*2)d6 ()]
```

In the first case, it appears that only the first 2 dice expressions are used, and in the second case, the "d6" term is ignored entirely. However, modifying these expressions by adding a leading constant term causes them to be evaluated correctly:

```
$ dice '0+d4+d6+d8+d10+d12'
Result: 23 - details:[0+d4+d6+d8+d10+d12 (d:(3) - d:(6) - d:(7) - d:(1) - d:(6))]
$ dice '(0+(3+4)*2)d6'
Result: 59 - details:[(0+(3+4)*2)d6 (3 5 4 2 6 3 5 6 5 6 5 2 6 1)]
```

**Comment by obiwankennedy** [comment]
Yes, there is a bug with no dice number command. 
If you roll: 1d4+1d6+1d8+1d10+1d12, instead of d4+d6+d8+d10+d12. It will go well.

**Comment by DarwinAwardWinner** [comment]
In fact, just adding a 1 to either of the first 2 terms is sufficient to get the correct behavior, e.g. "d4+1d6+1d8+d10+d12". 

By the way, did you mean to close this issue with c4b9d5ff34b49715853b362376cf519408739954? The commit message says "partial fix" but it looks like Github saw the word "fix" and closed the issue.

**Comment by obiwankennedy** [comment]
Github is stupid sometime.
I still have to fix the `(3+4)*2)d6` error.

**Comment by obiwankennedy** [comment]
Ok, I just commit change to fix `((3+4)*2)d6`. 
Let me know if you have any other remarks.

**Comment by DarwinAwardWinner** [comment]
The fix for parenthesized expressions seems to work for me. The issue with expressions like `d4+d6+d8+d10+d12` remains. I've also found some other variations on this expression that fail in new and interesting ways:

```
$ dice 'd4+d6+d8+d10+d12' # Original example
Result: 3 - details:[d4+d6+d8+d10+d12 (d4:(2) - d6:(1))]
$ dice '(d4+d6)+d8+d10+d12' # Parens around 1st 2 terms
Result: 3 - details:[(d4+d6)+d8+d10+d12 (3)]
$ dice '(1d4+d6)+d8+d10+d12' # Parens around 2 terms and a dice count on first term
Result: 6 - details:[(1d4+d6)+d8+d10+d12 (d4:(1) - d6:(1) - d8:(3) - d10:(1))]
$ dice '(d4)+d6+d8+d10+d12' # Parens around 1st term only
Result: 8 - details:[(d4)+d6+d8+d10+d12 (d4:(1) - d6:(4) - d8:(3))]
```

**Comment by DarwinAwardWinner** [comment]
Also, I'm not sure if this is related to any of the above, or if it is intentional, but the parser doesn't seem to care about unmatched parens:

```
$ dice '(1d4+1d6+1d8+1d10+1d12' # Unmatched open paren
Result: 23 - details:[(1d4+1d6+1d8+1d10+1d12 (d4:(1) - d6:(6) - d8:(5) - d10:(2) - d12:(9))]
$ dice '1d4+1d6+1d8+1d10+1d12)' # Unmatched close paren
Result: 24 - details:[1d4+1d6+1d8+1d10+1d12) (d4:(3) - d6:(5) - d8:(2) - d10:(5) - d12:(9))]
```

In both examples above, it still returned the "correct" result. However, it's also possible to make it return the wrong result:

```
$ dice '1d4+1d6+1d8)+1d10+1d12' # Unmatched close paren in the middle
Result: 11 - details:[1d4+1d6+1d8)+1d10+1d12 (d4:(2) - d6:(6) - d8:(3))]
$ dice '1d4+1d6+(1d8+1d10+1d12' # Unmatched open paren in the middle
Result: 9 - details:[1d4+1d6+(1d8+1d10+1d12 (d4:(4) - d6:(5))]
```

**Comment by obiwankennedy** [comment]
In fact, DiceParser has been designed to be really tolerant to errors. So, It parses as much as it can, and it runs what it understood. 
So, I should add error message to say: "parts of the command were not understood".

The error when there is no number before the dice operator, is not really an error. It is wrong to not set 1 before dice. I let this because it is helpful but in reality, it is a bad habit. I always thought about removing this feature.

**Comment by DarwinAwardWinner** [comment]
Yeah, I think it's fine if you give the result but add an additional warning when it doesn't parse correctly. As for considering a dice expression with no leading number as invalid, that's fine, but I think the bug/error is that sometimes it returns a correct result, and sometimes it wrong result with no error message indicating that something may have gone wrong. I guess the same error message is also applicable here: "parts of the command were not understood". Although that error message may be confusing to someone used to "dX" as a shorthand for "1dX".

**Comment by obiwankennedy** [comment]
I commit some changes, to display warning message and d4+d6+d8+d10+d12 command.

It fixes this issue hopefully.

**Comment by DarwinAwardWinner** [comment]
It looks like `1d4+1d6+(1d8+1d10+1d12` still returns a wrong result with no warning message. Other than that, I think all the above examples either return a correct result or a wrong result with a warning message.

**Comment by DarwinAwardWinner** [comment]
Yep, I confirm that fixes the missing close paren case. However, while testing that I ran into one more odd case:

```
$ dice '1d4+1d6+(1d8+1d10)+1d12'
Result: 27 - details:[1d4+1d6+(1d8+1d10)+1d12 (d4:(1) - d6:(3) - d12:(6))]
```

This one is a bit weird and maybe unrelated, because it looks like the result is actually correct, but the details are just missing the dice from inside the parens.

**Comment by obiwankennedy** [comment]
in fact, the parentheses and the addition operator are two levels  above the dice result (see the picture).

The result is good, but the addition node only add into result's chain its own result. It should add its whole internal chain. 

![file](https://user-images.githubusercontent.com/69177/49871856-a8882e00-fe17-11e8-92d8-fbc8d8f414e3.jpg)

**Comment by obiwankennedy** [comment]
The original bug is fixed on master on the new git repo: https://invent.kde.org/rolisteam/rolisteam-diceparser
