### ISSUE TITLE
Warning with comments

### ISSUE THREAD

**Issue by ditto13** [Rolisteam/DiceParser#24]
Recently Diceparser is throwing warning messages due to extra comments, despite the comment being behind a # character:

![image](https://user-images.githubusercontent.com/46005710/50240172-17263800-0392-11e9-92c4-6f2e3c761e77.png)

![image](https://user-images.githubusercontent.com/46005710/50240196-26a58100-0392-11e9-87ea-437bac7e7240.png)

also tried with space after #:

![image](https://user-images.githubusercontent.com/46005710/50240352-90258f80-0392-11e9-9ef2-942ac2185b17.png)

to confirm: Dec 18, @9 pm EST it was working fine, warnings started *am EST, Dec 19.
Seems something changed between there?

**Comment by obiwankennedy** [comment]
Should be fixed.

**Comment by ditto13** [comment]
Confirmed !  Thanks!

Curious .. what was root issue ?

**Comment by obiwankennedy** [comment]
DiceParser works like it is eating the command. 
When it understands the first character, this character is removed from the command line. 
And if it did not understand the rest of the command, it stopped the parsing and ran the command without displaying any warnings about "that part of the command has been ignored". 
For example: 
!1d6¿3 
It would had understand 1d6, and run it but ¿3 would have been completely ignored, without user notification about it. So now, you are noticed when the whole command is not understand.

So i had management of that. At the end of the parsing step, if the command still contains characters that means not the whole command has been understood. 
But the reading of comment did not removed the comment from the command line. I just fix the coment reading to remove the comment from the command.

**Comment by ditto13** [comment]
Ah, makes sense .. thanks for quick response and explanation! :)
