### ISSUE TITLE
Discord bot not responding to rolls?

### ISSUE THREAD

**Issue by ericastor** [Rolisteam/DiceParser#25]
As of right now, on my Discord server, the bot does not respond to rolls of the form `!5d6`... but it DOES respond correctly to `!macro list`.

**Comment by ericastor** [comment]
Invite available on request for testing. I'm reachable on Discord as Annon#5932.

**Comment by ElkHunter11** [comment]
It seems to be fixed

**Comment by ericastor** [comment]
So it is!

**Comment by obiwankennedy** [comment]
I install Qt5.12 on my computer and I removed Qt5.11. DiceParser was based on 5.11. I recompile it with 5.12 and it is ok.
