### ISSUE TITLE
port to TeamSpeak

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/DiceParser#26]
Hi,

Will it be ported to TeamSpeak ?

**Comment by obiwankennedy** [comment]
I don't know the TS3 API to make bot. I guess it is more complex than on discord. 
Not my priority. If your feature request gets many  comment and this is asked a lot. Then I wil do it.

**Comment by obiwankennedy** [comment]
I will give you a final answer to your question: 

No, I won't port diceparser on TeamSpeak. But,  you can probably make a plugin that call diceparser from system() C call.
You have to compile diceparser on your platform, install it, and then write down a c plugin to call it. 

It should not be that hard.
But It is not my priority it will never be.
Sorry.
