### ISSUE TITLE
how to roll several dices each is max of 2?

### ISSUE THREAD

**Issue by frakc** [Rolisteam/DiceParser#28]
rule state sthat player rolls 3d10+2, and for each of that dices players throws 2 dice and select max.
e.g.
first roll: 4,2=4
second roll: 1,10=10
third roll: 9:9=9
and expected sum 4+10+9+2 = 25

i tried
!2d10k1;2d10k1;2d10k1;mk1
but no sesponse from bot
```
!2d10k1;2d10k1;2d10k1;$1+$2+$3+2
# 4,10,10,26
Details:[2d10k1;2d10k1;2d10k1;$1+$2+$3+2 (4 - 9 - 3 - 10 10 4)]
```
this work but it is pretty inconvinient to write (akso first 3 results are redundunt) , especially if there will be more dice. Is there more correct way to solve such problem?

**Comment by obiwankennedy** [comment]
basically:

`2d10k1+2d10k1+2d10k1+2` should work, but it does not. It is a bug.

However, `!2d10k1;2d10k1;2d10k1;$1+$2+$3+2;"Final result: $4"` will show you readable result. 
Don't forget that you can set macro to run command by writing short command.

```
!macro ([0-9]+)!([0-9]+)  \1d10k1+\1d10k1+\1d10k1+\2;"Final result: $4" 1
then writing:
!2!1
will roll:
2d10k1+2d10k1+2d10k1+2;"Final result: $4"
```

**Comment by frakc** [comment]
thanks you.
Can you please guide me to docs about macro?  Is it possible to name them?

**Comment by obiwankennedy** [comment]
https://github.com/Rolisteam/DiceParser/blob/master/HelpMe.md#macro-management

Sure!

**Comment by frakc** [comment]
1 There is some error in your proposition
!2d10k1;2d10k1;2d10k1;$1+$2+$3+2;"Final result: $4"
```
Warning: Unexpected character at 4 - end of command was ignored "d10e10k1;2d10d10e10k1;2d10d10e10k1;$1+$2+$3+2;"Final result: $4""

# 16
Details:[2d10d10e10k1;2d10d10e10k1;2d10d10e10k1;$1+$2+$3+2;"Final result: $4" (9 7)]
```
2 how can i make variable number  of dice? eg if i need to roll 4 dice which follows same rule. Is making separate macro for each dice count only way?

**Comment by obiwankennedy** [comment]
You can set macro like this:

```
!macro ([0-9]+)w([0-9]+) \1d10k1;\1d10k1;\1d10k1;$1+$2+$3+\2;"Final result: $4" 1
```
So calling: `4w3` will roll:  `4d10k1;4d10k1;4d10k1;$1+$2+$3+3;"Final result: $4"`
