### ISSUE TITLE
cancelations on small valaues

### ISSUE THREAD

**Issue by frakc** [Rolisteam/DiceParser#29]
I have problem that following schema is often cancelled on discord bot
!Xd10;$1c[=10];$2d5

it generally works when X>=6,  and does not work if X <6 or X>= 10
note there is no response for  results 2,3,4,5 and that behaviour pretty consistent

![- discord](https://user-images.githubusercontent.com/1126230/52637622-698a5d80-2ed8-11e9-8679-cb2bd30b1649.png)

**Comment by obiwankennedy** [comment]
Look the result, it only works when you roll a 10 in the first part of the command as I said here: https://github.com/Rolisteam/DiceParser/issues/27#issuecomment-462735943

**Comment by frakc** [comment]
thank you did not undestand at first but now i got it
