### ISSUE TITLE
Hey, I have a question about qtquickcompiler to ask

### ISSUE THREAD

**Issue by begoat** [Rolisteam/DiceParser#3]
I saw you add a line `#find_package(Qt5QuickCompiler)` in CMakeLists.txt.
I am trying to import QtQuickCompiler into my project but I cannot find Qt5QuickCompiler.cmake 
So weird, so i wanna know can you use that ?

**Comment by obiwankennedy** [comment]
I think the Qt5QuickCompiler is available only with commercial version of Qt5. 

See https://www.qt.io/licensing-comparison/ (section tooling) for more details.

**Comment by begoat** [comment]
Thank you
