### ISSUE TITLE
Is it possible to include caller name in comment?

### ISSUE THREAD

**Issue by frakc** [Rolisteam/DiceParser#30]
I'ld like to add player name who runs command to bot respons on discord. So if all players will roll in same time, it will be cler who has which result.

**Comment by caitlynb** [comment]
Voting for this if such a thing exists!
(Thanks for the plugin!)

**Comment by obiwankennedy** [comment]
You can ask to your player to do it.

!1d100 # @Obi#1138 
It works,  I know it is not perfect, but it breaks the ambiguity

**Comment by MrMcX** [comment]
@obiwankennedy Is it possible to set the name automatically in a macro?

**Comment by JoeGans** [comment]
> @obiwankennedy Is it possible to set the name automatically in a macro?

Yeah, that would be a great addition to macro's, if it could automatically capture the username of the person using the macro command!

**Comment by LukeZS** [comment]
Yes please! It would be very useful :)

**Comment by obiwankennedy** [comment]
I will make that after the covid-19 pandemic, the bot is under heavy use, right now,  If I broke something for 2 mins, I'm scared to be sentenced to death.

**Comment by LukeZS** [comment]
Ok, thanks! I was hoping to use this feature during the codiv19 months, but we'll wait.

**Comment by fily1212** [comment]
Yes, really like this planned feature! Today I want to write a macro adding the name of the user, so if it will be possible to use $user, it will be great!

**Comment by obiwankennedy** [comment]
It is ready on my side, I will deploy it at the end of this week. It will come along with several other changes.
I rewrite part of the bot about management of subcommands.

**Comment by obiwankennedy** [comment]
This feature has been deployed.

![image](https://user-images.githubusercontent.com/69177/83747154-819f6680-a660-11ea-9ee7-b7bb1e4a7500.png)

**Comment by JoeGans** [comment]
Thanks Obi! ... Walts

**Comment by fily1212** [comment]
Hello! Thank you for your working! But I think it works only in a simple dice roll and with #, correct?
For example this doesn't work:
```
!1d6; "hello $user, $1"
```

**Comment by obiwankennedy** [comment]
Yes, it is only supported as the comment of the command.
