### ISSUE TITLE
trim spaces 

### ISSUE THREAD

**Issue by frakc** [Rolisteam/DiceParser#31]
!macro  ([0-9]+)s([0-9]+) \1d10;$1c[=10];$2i:[>0]{$2d5};$1+\2;"normal damage $4, critical damage $3" 1
!macro ([0-9]+)s([0-9]+) \1d10;$1c[=10];$2i:[>0]{$2d5};$1+\2;"normal damage $4, critical damage $3" 1

there is an extra space in first command (which is not very visible in discord text
if i run first command and then request macro list  macro will be 
```
id: 2 Pattern:  Command: ([0-9]+)s([0-9]+) \1d10;$1c[=10];$2i:[>0]{$2d5};$1+\2;"normal damage $4, critical damage $3" Regexp: True
```
instead of
```
id: 3 Pattern: ([0-9]+)s([0-9]+) Command: \1d10;$1c[=10];$2i:[>0]{$2d5};$1+\2;"normal damage $4, critical damage $3" Regexp: True
```

can you please trim spaces?

**Comment by obiwankennedy** [comment]
Where is the extra space in the first command? 
I copy paste both command in text editor and they look good to me.
