### ISSUE TITLE
yesterday bot did not react many times

### ISSUE THREAD

**Issue by frakc** [Rolisteam/DiceParser#32]
Ocasionally bot did not respond for ~5 minutes  in random time of game. 

![- - discord](https://user-images.githubusercontent.com/1126230/52712544-9785a580-2f9d-11e9-9aea-9024e4cad107.png)

**Comment by obiwankennedy** [comment]
Which time zone are you ?

Yesterday I forced re-connection of all the bots, re-connection can take time

**Comment by frakc** [comment]
+2 UTS
