### ISSUE TITLE
Aliases are removed

### ISSUE THREAD

**Issue by Deerinspotlight** [Rolisteam/DiceParser#33]
This is a great bot for a game I'm running on discord, but whenever I create new alias commands they seem to stop working after a few days and I end up having to remake them. Is this intentional? It would be convenient if they could remain permanent until removed by the users

**Comment by obiwankennedy** [comment]
no, it is not intentional. It is alias or macro ? (just to be sure some users are confused with this two kind of shortcut).
Do you know the id of your server ? ( a huge number from discord). My bot saved aliases inside a file.
aliases are stored by server ID.

**Comment by Deerinspotlight** [comment]
Thank you for responding!
It's the !alias function. I haven't really tried messing with macros yet. 
The server ID is 548945230791966720

**Comment by obiwankennedy** [comment]
I have no aliases recorded for this server id. 
Don't hesitate to join rolisteam's discord server to send and invitation to me to you server. Then I will be able to make some tests. 
But aliases for my own server are still there.

**Comment by Forekast** [comment]
Alias lists do seem to disappear / be purged whenever a new build is pushed

**Comment by obiwankennedy** [comment]
Not exactly, I run the bot from another computer for few days, so I run an old version of the bot and its data, so yes some macros are purged. I have to make a way to deploy back up with updated data.

**Comment by obiwankennedy** [comment]
Aliases are now stored in database.
