### ISSUE TITLE
Discord: broken examples in HelpMe.md

### ISSUE THREAD

**Issue by Hermesiss** [Rolisteam/DiceParser#40]
I have tested in Discord all examples (except really large ones) from https://github.com/Rolisteam/DiceParser/blob/master/HelpMe.md
Some are broken
- [ ] `10d10o` (and others in Occurence)  - `Warning: Unexpected character at 5 - end of command was ignored "o"`
- [x] ~~`4d6e6u6k3` - `Warning: Unexpected character at 6 - end of command was ignored "6k3"`~~
- [x] ~~`8d10;$1c[>6];$1c1;$2-$3i:[>0]{"%3 Success[%2]"}{i:[<0]{"Critical fail %3 [%2]"}{"Fail %3 [%2]"}}"` - `Warning: Unexpected character at 96 - end of command was ignored """`~~

**Comment by obiwankennedy** [comment]
for this one: 8d10;$1c[>6];$1c1;$2-$3i:[>0]{"%3 Success[%2]"}{i:[<0]{"Critical fail %3 [%2]"}{"Fail %3 [%2]"}}"
it is just an extra " at the end.

**Comment by obiwankennedy** [comment]
For "4d6e6u6k3", it is a mistake because u operator does not take any parameters so the command is just: "4d6e6uk3"

But I will change the operator to y, and u operator will remove all dupplicates

**Comment by obiwankennedy** [comment]
For the Occurence, the job is working in the occurence branch but I did not merge it. So I just have to do that to make it work.

**Comment by obiwankennedy** [comment]
You can try now, the o operator should work fine. 





By the way, you should change your git credential, because rolisteam is now a kde project, and kde requires commit to have real name. The author name of your commits is "Alex", it is better to set "Alex H" or something.
I personnally use "Renaud G." and it is enough.

**Comment by Hermesiss** [comment]
Everything is working now
