### ISSUE TITLE
Curly brace artifact in output code

### ISSUE THREAD

**Issue by Forekast** [Rolisteam/DiceParser#43]
For $X{Y}, where X>=10 && Y is any, an excess '}' is generated after normal output.

Example:
Expected output of `$15{3}` might be `006` but instead outputs `006}`

Thanks

**Comment by obiwankennedy** [comment]
I can't reproduce, could you give me a full command example ?

**Comment by Forekast** [comment]
```
!1d6;1d6;1d6;1d6;1d6;1d6;1d6;1d6;1d6;1d6;1d6;1d6;1d6;"$1{3} $2{3} $3{3} $4{3} $5{3} $6{3} $7{3} $8{3} $9{3} $10{3} $11{3} $12{3} $13{3} "
```

**Comment by obiwankennedy** [comment]
I did not deploy the solution yet. it will be done in the week end i think.
