### ISSUE TITLE
macro list & discord character limit

### ISSUE THREAD

**Issue by Forekast** [Rolisteam/DiceParser#45]
This is likely more of a Discord issue than a DiceParser issue, but it affects DiceParser.

`!macro list` no longer shows up on our server when the command is entered. This started happening after adding a macro to an already long list of macros. Removing that macro allows `!macro list` to display correctly again. 

I have recently learned that Discord has a character limit of 2000, so this may very well be the reason that `!macro list` does not show after adding too many macros to the list, going past the cap.

I don't know if Discord will ever extend this limit. Would you be able to implement something to detect when `!macro list` is too long to display on Discord and instead output it across multiple messages?

**Comment by obiwankennedy** [comment]
Sure it can be done.

**Comment by foreverperfectxi** [comment]
I know this is about a year old, but I think I've recently encountered this same issue with `!alias list`. There are quite a few very long aliases on our server and I believe as a result we can no longer get discord to return the list. Obviously more of a problem with discord than the bot, but some kind of fix or work around would be lovely.

**Comment by obiwankennedy** [comment]
I have a nev version of the bot to be deploy soon. The new version brings many feature but it also brings new fashion for manage some command and it will be so easy to extend command.
But, the bot is under heavy use right now. I prefer to deploy important change when the situation will be less serious.

**Comment by obiwankennedy** [comment]
I just deploy new version which send text file when the message is too long.
I will close this ticket.
