### ISSUE TITLE
For loop?

### ISSUE THREAD

**Issue by lekyryu** [Rolisteam/DiceParser#46]
Is there a way to do a for loop?

20th anniversary WoD rules have 10s on specialties counting as 2 successes and 1s taking the whole dice away. 

I.e. a 4d10 that throws 1,1,10,10 

Should be 0 successes as the ones cancel the tens even if they have specialties. 

What I tried doing was a for roll that for each one it would take one successful result starting from the lowest number to the highest

**Comment by obiwankennedy** [comment]
You can easily manage this 20th anniversary WoD but you need another approach.
I write down in multi line format with comment for better understanding. 

4d10; # roll dice
$1c10; # count 10s
$1c1; # count 1s
$1c[>=6&<10]; # count success but does not count 10s
$2-$3; # substract the 1s count to 10s count
$5i:[>0]{$5}{0}; # useful if 1s take away only 10s
$6+$6+$4; # sum twice the 10s rest and the successes count.
$7i:[>0]{"$7 Successes [%2]"}{"You fail [%2]"} # display 

so now in one line:

!4d10;$1c10;$1c1;$1c[>=6&<10];$2-$3;$5i:[>0]{$5}{0};$6+$6+$4;$7i:[>0]{"$7 Successes [%2]"}{"You fail [%2]"}

then you may want to make macro:

!macro ([0-9]+)w([0-9]+) \1d10;$1c10;$1c1;$1c[>=\2&<10];$2-$3;$5i:[>0]{$5}{0};$6+$6+$4;$7i:[>0]{"$7 Successes [%2]"}{"You fail [%2]"} 1

To call it:
!4w6
First parameter is the number of dice, the second is the difficulty.

**Comment by lekyryu** [comment]
I think it isn't activating the $-2-$3 part as it's not taking away successes with ones

**Comment by obiwankennedy** [comment]
yes, if only compare value in front of him.

I did not try my examples, I just make them as i would do it. But your second example, is normal because I was not sure 1s remove only 10s or 10s first and then normal successes. 
I have to fix the command to manage that. Are there any other rules I should know about ?

**Comment by obiwankennedy** [comment]
```!4d10;$1c10;$1c1;$1c[>=6&<10];$2-$3;$5i:[>0]{$5}{0};$6+$6+$4;$7i:[>0]{"$7 Successes [%2][$1,$2,$3,$4,$5,$6,$7]"}{"You fail [%2][$1,$2,$3,$4,$5,$6,$7]"}```

> 1 Successes [5,3,8,3][19,0,0,1,0,0,1
This example is correct, right ?

**Comment by obiwankennedy** [comment]
> **2 Successes [8,5,1,8][22,0,1,2,-1,0,2]**

This example is wrong given your rules.

**Comment by obiwankennedy** [comment]
!4d10;$1c10;$1c1;$1c[>=6&<10];$2-$3;$5i:[>0]{$5+$5}{$5};$6+$4;$7i:[>0]{"$7 Successes [%2][$1,$2,$3,$4,$5,$6,$7]"}{"You fail [%2]"}

(I fixed the command)
> **1 Successes [1,8,10,3][22,1,1,1,0,0,1]**

it seems correct to me.
