### ISSUE TITLE
Assistance with a Macro

### ISSUE THREAD

**Issue by ninjatommy21** [Rolisteam/DiceParser#47]
I'm still rather new to DiceParser and I haven't quite figured out how to use it. From my understanding it can create some complex dice rolls and that's what I'm hoping for.

In a group I have we created a custom mind control effect with the following
Roll 1d100
1-5 : full fail
6-50 : temp fail
51-95 : temp pass
96-100 : full pass
However on each temp fail or temp pass it increased that full section by 10.
so 1 full pass changes the full pass to 86-100 and the temp pass to 51-85

I'm wondering if it would be possible to use a macro to list how many temp passes and fails you have thus far and have the string adjust what numbers would result in the new roll
thus when it's 0 for both and you roll a 51 it spits out Temp Pass. 
But if you have it at 3 temp passes when you run the macro and roll a 77 it will spit out full pass and not temp pass.

This might be unrealistic. However I'm not quite sure as I'm unsure of the capabilities of the Macro Function. 

Thank you for your time. 
Also. If anyone has any good videos or sources to better explain the Macro Function I'd appreciate it. I can't seem to find any.

**Comment by obiwankennedy** [comment]
Are you sure of your example?
As far as I understood, rolling 77 after 3 temp pass, should give a temp pass.

51-95
After one temp pass it becomes
46-100 or 41-95
Second one:
36-95.

DiceParser won't be able to store  previous rolls or values. 
But it is possible to pass modificaters and compute appropriate range

**Comment by ninjatommy21** [comment]
I went ahead and closed this as I found another solution using DiceParcer and Google Sheets.

To clarify. The temp pass or temp fail regions would never increase. Receiving those rolls increase the full pass and full fail regions. 

!d100i[>95]{"full pass %1"}i[>50]{"temp pass %1"}i[>5]{"temp fail %1"}{"full fail %1"}

This is the base that it's using. 
Using Google sheets i can set up ifs statements regarding cells that players can input how many temp passes and temp fails they have received. 

Thus is they 2 temp fails and 3 temp passes the Google sheet will output the following
!d100i[>65]{"full pass %1"}i[>50]{"temp pass %1"}i[>25]{"temp fail %1"}{"full fail %1"} 
For my players to use on the DiceParcer Bot.


The original idea was to see if it was possible to only use DiceParcer. Using the Macro Feature that allows you to submit 2 values that end up replacing values in the Macro. - The regular-expression

I played around with this and was able to figure out how it assigns the values. with the \1 and \2 in the example provided on the Documentation.

However I was unable to figure out a way for it to edit roll result even with the ability to have the macro enter \1 and \2 as the number of times you have temp passed for failed

This is why I defaulted to using a combination of DiceParcer and Google Sheets.

**Comment by ninjatommy21** [comment]
![1](https://user-images.githubusercontent.com/53417848/62041569-93eb8100-b1c1-11e9-884d-d7da35637a65.PNG)
![2](https://user-images.githubusercontent.com/53417848/62041573-96e67180-b1c1-11e9-8411-0c7c83b7f24d.PNG)
![3](https://user-images.githubusercontent.com/53417848/62041577-99e16200-b1c1-11e9-8a17-d8705624117c.PNG)

The provided snippets are of the Google Sheet and the three formulas used for how I got my desired outcome.

**Comment by obiwankennedy** [comment]
You are on the right way. Give me some time and I will go back to you with macro that make the use of Google sheet less important and useful

**Comment by ninjatommy21** [comment]
Take your time. Thank you.

**Comment by obiwankennedy** [comment]
this macro:
```
!macro ninja([0-9+),([0-9+) d100;5+\1*5;96-\2*5;$1i[<$2]{"full fail $1"}i[<51]{"temp fail $1"}i[<$3]{"temp pass $1"}{"full pass  $1"} 1
```

to call it : "ninja0,0",  "ninja2,3" ....

**Comment by ninjatommy21** [comment]
This is perfect. It took a moment to understand why it wasn't working though. Seems a ] was missing after both the 9s.
Once I fixed that it worked perfectly. 
Thank you so much

**Comment by ninjatommy21** [comment]
There seemed to be some minor issues. However your code gave me an accurate example of how I can use the macro function. Thus I was able to reverse engineer it and change to numbers I needed to accordingly. 

And thanks to your help I now know how to do this in the future should I ever need something complex like this. 
Thank you So much
You are awesome!

**Comment by ninjatommy21** [comment]
!macro ninja([0-9]+),([0-9]+) d100;5+\1*10;95-\2*10;$1i[>$3]{"full pass $1"}i[>50]{"temp pass $1"}i[>$2]{"temp fail $1"}{"full fail $1"} 1

the different is that the change is suppose to be by 10 and not 5. And I've set them in greater than order. Personal preference. 
Functions the same.

**Comment by ninjatommy21** [comment]
I do have another question. Is it possible to set it so nothing above a certain number is accepted. 
The way this works that that have any number above 4 would essentially break the code.

And if you can limit it would it be as follows. 
ninja([0-4]+),([0-4]+)

or

ninja([0-4]),([0-4])
?

**Comment by obiwankennedy** [comment]
I think it is: 
ninja([0-4]),([0-4])

the + at the end means "At least one or more"

**Comment by ninjatommy21** [comment]
Thanks

**Comment by ninjatommy21** [comment]
`!macro ninja([0-9]+),([0-9]+),([0-9]+) d100+\3;5+\1*10;95-\2*10;$1i[>$3]{"full pass $1"}i[>50]{"temp pass $1"}i[>$2]{"temp fail $1"}{"full fail $1"} 1`

I've seem to run into another issue that I can't seem to get past. The issue occurs if it's ran as a macro. Or if I simplify it as a regular dice roll
`!d100+10;5;95;$1i[>$3]{"full pass $1"}i[>50]{"temp pass $1"}i[>$2]{"temp fail $1"}{"full fail $1"}`

It seems that any modification to the dice rolls breaks it. I've tested this using the $ command as well. To have the dice roll in the first instruction and then edit the value in the second. Doing either results in this break. Where is just lists the numbers. I've included two screenshots to show this off. 
If it isn't possible to edit the roll let me know as this limits other possible macros. Such as tests of strengths between players both using their buffs. 

![4](https://user-images.githubusercontent.com/53417848/62106420-cbface80-b26a-11e9-83c1-2d2fa0caadec.PNG)
![5](https://user-images.githubusercontent.com/53417848/62106427-d2894600-b26a-11e9-93b8-c37328af54b5.PNG)

**Comment by obiwankennedy** [comment]
!1d100+10;5;95;$1i:[>$3]{"full pass $1"}{$1i:[>50]{"temp pass $1"}{$1i:[>$2]{"temp fail $1"}{"full fail $1"}}}

**Comment by obiwankennedy** [comment]
With more details, as you put +10 at the end of dice roll, it change the result type from dicelist to number. And the bare if expects a dicelist as previous node.
The : asks the ifs to evaluate on number value

**Comment by ninjatommy21** [comment]
Thanks. 
This worked wonders and I was able to put it to work on other macros. I appreciate all your assistance!
