### ISSUE TITLE
Adding to dice before Explodo!

### ISSUE THREAD

**Issue by JoeGans** [Rolisteam/DiceParser#48]
Looking to roll the following ... **!(1+1d10)e>3** ... where the 1 is added to the d10 **before** the
Explode operator is checked, but it adds the 1 **after** the explode checks the valid?

Example: https://discordapp.com/channels/500738737169235968/571745040137846784/609612407718936596

Am i writing this die roll wrong? Thoughts, feedback appreciated! ... Walts

**Comment by obiwankennedy** [comment]
There is some issue with your command.
e is what we called a dice option. It's only work on dice, meaning the previous part of the command must finish with a dice result. 

The result of "1d10" is a **dice result**.
The result of "1+1d10" is a **number result**.

The proper way to make your command working is: 

```
!1+1d10;$1i:[>3]{+1d10e[>3]};"final result: $2"
```

**Comment by JoeGans** [comment]
Hey obi ...Thanks for that. 

I made an effort to read the HelpMe.md file and realised a simpler command
 could be type (and remembered!) using the Range format ...

!1d[2-11]e>3

... so 1+1d10 would be 2-11. Thanks for helping ... Walts

**Comment by obiwankennedy** [comment]
Yes, it also another way to do so.
The right command is: 
**!1d[2-11]e[>3]**
