### ISSUE TITLE
Operator "a" don't stack

### ISSUE THREAD

**Issue by robinmoussu** [Rolisteam/DiceParser#5]
Hello,
In the dice system I use with friend, when a D10 make a 10, you re-roll it if you make a 10, and add the result. This operation is done endlessly.
Example: I need to roll 5 dices. I get:
`1 2 10 10 10`
I got some 10, I re-roll them:
`- -  4 10 10`
What a lucky bastard I am! Still some 10 to re-roll:
`- - -  2  8`
Now it's ended.
I would like to be able to have rolisteam displaying:
`1 2 14 [10,4] 22 [10,10,2]  28 [10,10,8]`

So I tried to do (I give the following command with 1d2 to make it more obvious to test:
 `!1d2a[=2](1d2)`
The possible result are `1`, `3 [2,1]`, `4 [2,2]`
It's working so far. But if I try to make it chain, I wasn't able to do it:
` !1d2a[=2](1d2a[=2](1d2))`
This pattern never roll the third dice, even if I got `4 [2,2]` witch should be either `5 [2,2,1]` or `6 [2,2,2]`.

And even if it was working, it is still not optimum since this mean that I still need to re-write the pattern multiple time to be sure that a dice can be re-rolled enough time (I will create an alias anyway, so it's not such a big deal). Ideally I would love to have a `A` operator to apply the add on the result, so the following command would exactly match our dice system:
`!1d10A[=10](1d10)`

**Comment by robinmoussu** [comment]
I didn't understood correctly the semantic of the `a` operator.

**Comment by obiwankennedy** [comment]
I think what you want is the reroll operator r instead of a.
A means add.  It is like the r operator except it only works once.

**Comment by obiwankennedy** [comment]
Oups i got confused,  the right one is e operator.
