### ISSUE TITLE
A Multiple Success/Failure Level Dice Roll?

### ISSUE THREAD

**Issue by JoeGans** [Rolisteam/DiceParser#55]
Hi Guys

I wonder if someone can help with this dice roll dilemma of multiple success/failure levels?

In our game of Trudvang Chronicles RPG, the d20 is rolled against the following ...

```
1 (or 2 Hwitalja) = Perfect success.
≤ SV = Success.
> SV = Failure.
20 = Fatal failure.
```

... so, I'd like to reflect this in my dice roll, with the SV being passed as a changing parameter number?

Any refs to this at all or suggestions? I'd like the dice roll to display the txt message result, eg "Perfect success" if a 1 or 2 is rolled.

Advice/pointers appreciated ... Walts

**Comment by obiwankennedy** [comment]
The command you want if SV = 12

`!1d20;$1i:[<=2]{"Perfect Success: $1 "}{$1i:[<=12]{"Success $1 [%2]"}{$1i:[=20]{"Fatal Failure $1"}{"Failure: $1"}}}`

# The macro you want:

```
!macro vang([0-9]+) 1d20;$1i:[<=2]{"Perfect Success: $1 "}{$1i:[<=\1]{"Success $1 [%2]"}{$1i:[=20]{"Fatal Failure $1"}{"Failure: $1"}}} 1
```

# To call it:
!vang12

**Comment by JoeGans** [comment]
Fantastic, works a treat! :o]

Minor tweak, to allow for 2, 3 or more d20's all being rolled together? eg, !macro vang([0-9]+) **#**d20 ... pass how many d20's get rolled?

Many thanks, Walts

**Comment by obiwankennedy** [comment]
you want to roll several d20s, but for each you want the result?

3d20...

Sucess, Perfect Success, Failure...

or do we sum up the 3 dice ?

**Comment by JoeGans** [comment]
Looking for the individual results for each, so three (or more) dice would produce
three (or more) results, rather than a single total ... Thanks, Walts

**Comment by obiwankennedy** [comment]
I fixed the issue partially. Still working on it.

**Comment by obiwankennedy** [comment]
Ok

This command works like a charm:
```
2d20i[<10]{"low"}{i[<15]{"high"}{"very high"}}
```

I have to test the behaviour with instructions:
2d20;$1i:[<=2]{"Perfect Success: $1 "}{$1i:[<=\1]{"Success $1 [%2]"}{$1i:[=20]{"Fatal Failure $1"}{"Failure: $1"}}}

After that, I will deploy the solution, and the fix will be available in discord.

**Comment by JoeGans** [comment]
Thanks Obi, your effort is greatly appreciated! ... Walts

**Comment by JoeGans** [comment]
Thanks Obi, your effort is greatly appreciated! ... Walts

**Comment by JoeGans** [comment]
OPP's, sorry about that ... too early in the morning for me! ;) Walts

**Comment by OrangeMush28** [comment]
Having a similar issue trying to figure it out 
Crafting mechanic roll 1d20 + skill bonus if 10 greater than craftDC = MasterWork; if >= DC = Success, if 10 or more below DC Fragile. Tried using the macro above and it is giving line error 4 with !macro Smith([0-20]+)... Call line !Smith15 ignoring "h15"
