### ISSUE TITLE
Questions regarding compatibility with Roll20

### ISSUE THREAD

**Issue by DonaldTsang** [Rolisteam/DiceParser#58]
The dice notation in DiceParser looks pretty similar to https://wiki.roll20.net/Dice_Reference
(for reference the source code is at https://app.roll20.net/assets/dengine.js?v=123)
Is it possible to have formula compatibility, or at the very least feature parity between DP and R20?
Similar discussion has been made in https://github.com/GreenImp/rpg-dice-roller/issues/60

**Comment by DonaldTsang** [comment]
See https://github.com/the-nick-of-time/DnD/issues/2 and https://github.com/skizzerz/DiceRoller/issues/6

**Comment by obiwankennedy** [comment]
DiceParser is the software component which rolls dice in **Rolisteam**.
It has been developed as stand alone component, so it is easy to integrate it inside other project.
Such as DiceParser the discord bot.

My DiceParser bot is used by 50 000 discord servers. My user are used to diceparser syntax. So I won't break anything to respect Roll20 syntax. I don't want to define them as reference.

I will be glad to implement any wanted feature, but I won't do the comparison between DiceParser and Roll20, my self. My time is to precious.
