### ISSUE TITLE
Problem with expression and 'c' operator

### ISSUE THREAD

**Issue by vcrini** [Rolisteam/DiceParser#59]
> !d20c[>0]
As expected this is always 1 because result is always >= 1.
The same should be for 
> !d20+3c[>0]

but result is always 0
> # 0
> Details:[d20+3c[>0] ()]

It seems a bug. Also if it's written in equivalent form:
> !d20+3;$1c[>0]
> # 5,0
> Details:[d20+3;$1c[>0] (2)]

**Comment by obiwankennedy** [comment]
I will say it is normal but diceparser should display warning when you run this kind of command.

The C operator computes how many dice fit the condition. It is useless on scalar number.

The main issue with this command is that `!d20+3` as for final result a number, when "!d20" has a dice result array as final result.

`!d20c[>0]+3` works.
I don't know what you want to do but I think the If operator may help you. As It can compare any kind of result.

**Comment by vcrini** [comment]
Hi obiwankennedy thanks for your answer that helped me to sourt out the problem!
I'd like to explain what I'm trying to obtain:
I used (wrongly) this form because my goal is to 'script' on a single roll a hit to roll and if enemy is hit to roll the damage.
This what I was trying to do:

`!d20+3c[>11]; d10+3; $2*$3; "damage inflicted is: $4"`

this should ouput 0 if enemy is missed (it has AC 12) otherwise d10+3 damage is displayed.

I could use the 

`!d20c[>8]+3`

but is not optimal because I've to recalculate  condition to be hit (from >11 to >8).

Maybe I'm doing in the wrong way there is a more convenient way to obtain this?

**Comment by obiwankennedy** [comment]
The command you want to do is this:

```
!1d20+3;$1i:[>11]{1d10+3}{0};"inflicted damage: $2 details:[%2]"
```

First instruction, I roll the dice and add 3.
Second instruction, I compare the result of the first instruction to 11 and if it is greater I roll damage (1d10+3) or return 0 otherwise. 
Then, I finally print out the result.

Be careful, that the default parameter of 1 in `d10` does not work inside if instruction.
So, it is important to write `{1d10+3}`; because `{d10+3}` won't work.

**Comment by vcrini** [comment]
Thanks a lot for the solution!
