### ISSUE TITLE
Feature Request: List Aliases 

### ISSUE THREAD

**Issue by JustinClough** [Rolisteam/DiceParser#61]
Is it possible to add `!alias list` to list aliases similar to `!macro list`? Right now, AFAIK, the only way to know what aliases are added are to remember them the old fashion way. 

If it matters, I primary use the diceparser on discord. Let me know if I can provide any other info.

**Comment by killian-34** [comment]
Yes! This would be an awesome feature...

**Comment by obiwankennedy** [comment]
This feature already exists. 

https://discordapp.com/channels/279710365334372352/361139925053079562/686714960122085442

**Comment by killian-34** [comment]
> This feature already exists.
> 
> https://discordapp.com/channels/279710365334372352/361139925053079562/686714960122085442

Hmm that link is broken for me? Just takes me to an empty channel.

**Comment by obiwankennedy** [comment]
![Screenshot from 2020-03-10 00-56-29](https://user-images.githubusercontent.com/69177/76267157-1a913200-626a-11ea-83cb-c9e0b362b950.png)

**Comment by obiwankennedy** [comment]
But, if your alias is two big (more than 2000 characters) discord don't show the message as it is too long.

**Comment by JustinClough** [comment]
Thanks for the help! I just got it working on my discord server as well.
