### ISSUE TITLE
Exploding dice of different types in one roll

### ISSUE THREAD

**Issue by mzywiol** [Rolisteam/DiceParser#63]
In many systems (e.g. EarthDawn) you ofter roll a pool od different dice (e.g. 2d12+d10+d6) and all of them are exploded dice (exploding on the maximum result). I wish there was an option in DiceParser to do that easily.

The only way to do it now is to use the KX operator ("Explode and keep") for EACH type of dice and also to remember to add the number of dice again, like so:

`!2d12K2+d10K1+d6K1`

I would rather expect not to repeat the number of dice after K:

`!2d12K+d10K+d6K`

Or maybe even have some other operator. Maybe if the D in roll code is in uppercase it would mean exploded dice? Like so:

`!2D12+D10+D6`

**Comment by obiwankennedy** [comment]
If you want dice to explode, just use explode operator.

!2d12e12+1d10e10+1d6e6

Then with some alias you may be able to reduce the text length  you need to type.

`!macro ([0-9]+)D([0-9]+)  \1d\2e\2 1`

then you will have to type:
!1D12

**Comment by mzywiol** [comment]
Whoa, this works. Thanks, man!
