### ISSUE TITLE
Issue with 'rolling with parameters' on discord

### ISSUE THREAD

**Issue by ProfessorOcecat** [Rolisteam/DiceParser#65]
This may just be me misunderstanding the syntax, but according to the guide typing something such as '!4d[-1-1] or !2d[0-9] should roll with a range: however the diceparser returns this:
"Warning: Unexpected character at 6 - end of command was ignored "]"

# -7
Details:[2d[0-9] ()]"
I'm not sure if the issue is with me or the bot, but I feel like its the bot at the moment.
Doesn't work when I omit '[]' either, nor if I use any other type of bracket.

**Comment by obiwankennedy** [comment]
The range syntax has changed:

4d[-1..1]
.. instead of -.

**Comment by ProfessorOcecat** [comment]
Thanks: the help file may need updating then.
