### ISSUE TITLE
if statement used as example does not work

### ISSUE THREAD

**Issue by Jstenoien** [Rolisteam/DiceParser#68]
Hello, love this dice bot on Discord but as we were trying it out we noticed that this example from the HelpMe.md page does not actually work how it should:

    2d10i:[>15]{"Success %1 [%2]"}{"Fail %1 [%2]"}
    Same as above, but the result of each die is displayed inside square brackets.

The result of each die is not displayed inside square brackets, instead you get:
`Fail 7 []`

Thanks for your awesome work!

**Comment by OrangeMush28** [comment]
!2d10i:[>15]{"Success %1 [@2]"}{"Fail %1 [@2]"}

the % in the []'s needs to be @ and then it will display the die

**Comment by JoeGans** [comment]
Can I ask, If I change the 2d10i to 4d10i nothing happens ...

!4d10i:[>15]{"Success %1 [@2]"}{"Fail %1 [@2]"}

... Tried the following, with still no result...

!4d10i:[>15]{"Success %1 [@4]"}{"Fail %1 [@4]"}

... What am I missing? ... Thanks, Walts

**Comment by JoeGans** [comment]
This line works OK for my issue...

!4d10i:[>15]{"Success  %1 [$1] ~ [@1]"}{"Fail %1 [$1] ~ [@1]"}

**RESULT**
Success  19 [19] ~ [2,8,5,4]

... So, the @1 is the key to fix things? ... Walts

**Comment by obiwankennedy** [comment]
perhaps the introduction of @ place holder broke some stuff. I will check that.
