### ISSUE TITLE
Writing a multi 4 part pass/fail with user in put.

### ISSUE THREAD

**Issue by OrangeMush28** [Rolisteam/DiceParser#69]
Have been trying to get a line working to add a skill bonus to a d20 and have that check against a variable number depending on what the user enters in the command.

user entered information would be SkillB, itemSize, specialMaterial
 a rough break down:  d20+SB=X; if X>= IS+SM+10 True: "MasterWork $1" False: if X>=IS+SM True: "Success $1" False: if X<=IS+SM-10 True: "Failure $1" False: "Fragile $1"

I am having trouble being able to add the user input variables and if I !1d20+12;$1i[>=30]{"MasterWork Success: [@1] "}{$1i[>=20]{"Success [@1]"}{$1i[>=10]{"Fragile [@1]"}{"Failure: [@1}"}}} , it does not display any of the string from Trues or False just the result of the first instruction twice?

any thoughts or help is much appreciated

**Comment by JoeGans** [comment]
This seems to work fine...

!1d20+12;$1i:[>=30]{"MasterWork Success: [@1] "}{$1i:[>=20]{"Success [@1]"}{$1i:[>=10]{"Fragile [@1]"}{"Failure: [@1]"}}}

... Missing : after $1i and a wonky bracket } -> ] at the end? ... Walts

**Comment by JoeGans** [comment]
Actually, just tiedied up your string ... some : and a } -> ] where needed to fix things, but here's a working one, with some extra txt you can remove...

!1d20+12;$1i:[>=30]{"MasterWork Success ~ Dice Roll: [@1] ~ Total: [$1]"}{$1i:[>=20]{"Success ~ Dice Roll: [@1] ~ Total: [$1]"}{$1i:[>=10]{"Fragile ~ Dice Roll: [@1] ~ Total: [$1]"}{"Failure ~ Dice Roll: [@1] ~ Total: [$1]"}}}

... NOTE: [@1] shows the Dice Roll number, and [$1] shows the total, ie d20 **+ 12**

Hope that helps? ... Walts

**Comment by OrangeMush28** [comment]
That definitely cleans it up, thank you. Now for the second part that makes things tricky, making the +12 a user entered variable from 5-30. I assume this would either be using functions or macros or maybe a mix? In python I would be storing "alias's" that would correspond to item size(entered in roll command) to call up the DC(if) check values and compare to the d20+(users skill entered at command)  last time i played with the macro adding I killed the bots ability to recognize 1's and 0's in command text.

Thank you for fixing up the first lines

**Comment by JoeGans** [comment]
I'm not overlay clued up on macro's, but this works ... I've basically pinched it from another users string! ...

!macro DsRoll([0-9]*) 1d20+\1;$1i:[>=30]{"MasterWork Success ~ Dice Roll: [@1] ~ Total: [$1]"}{$1i:[>=20]{"Success ~ Dice Roll: [@1] ~ Total: [$1]"}{$1i:[>=10]{"Fragile ~ Dice Roll: [@1] ~ Total: [$1]"}{"Failure ~ Dice Roll: [@1] ~ Total: [$1]"}}} 1

**RESULTS**
!DsRoll
Fragile ~ Dice Roll: [10] ~ Total: [10]

!DsRoll**22**
MasterWork Success ~ Dice Roll: [14] ~ Total: [36]

... So, the range of 5-30 is what I'm not sure to set within a macro, but as you can see, the command !DsRoll**22** rolls 1d20+**22**, so it's obvious what the players added to his final roll?

Maybe someone more clued up can set that range for you?

Oh, and you can change the DsRoll to whatever txt you want ... Walts

**Comment by OrangeMush28** [comment]
> **PS**: _There seems to be a lack of real documentation on macro's, to be honest?_


That's what i was thinking and was why I asked my question cause, no idea how to get what I wanted out of it.  So the (+\) in the macro command is what signs the input replacement, and ([0-9]) makes the input an integer variable. I would have to assume as I thought it was the range available for input.   Thank you so much, i wasn't able to find anything in searching for how to things

**Comment by OrangeMush28** [comment]
@JoeGans would I be able to make this an alias with user entered variables? !craft(material [y/n])s([0-9]*) if material is y adding 5 to all if instructions?

**Comment by SaltatorMortis** [comment]
well in my honest opinion regex not good for this.
 use a number instead of Y/N

`craft\(([^ )]*)(?: (\d+))?\)(\d*)`
`1d20+\3+\2;$1i:[>=30]{"\1 with MasterWork Success ~ Dice Roll: [@1] ~ Total: [$1]"}{$1i:[>=20]{"\1 with Success ~ Dice Roll: [@1] ~ Total: [$1]"}{$1i:[>=10]{"\1 with Fragile ~ Dice Roll: [@1] ~ Total: [$1]"}{"\1 with Failure ~ Dice Roll: [@1] ~ Total: [$1]"}}}`

regex is incapable of an if command and rolistram can't output a Number with an if command on string
Sie erzielten n 1+1 beim Würfeln [1l[y,n]i:["y"]{1}{2};1d2;"$1+$2" (1)]
i think the macro engine should be more function based like anydice

**Comment by JoeGans** [comment]
Thanks for that, SaltatorMortis.

Would it be possible for you to describe what's going on in this new section ...  **craft\(([^ )]*)(?: (\d+))?\)(\d*)** ... and show an example of it working? Thanks, Walts

**PS**: _Is one of the ) in the right place after the ^ symbol?_

**Comment by SaltatorMortis** [comment]
the open bracket doesn't need to be escaped  inside a character class
but if you feel better you always can escape the letter with a \
it maches every character until it gets a space or closingbracket
you could replace `[^ )]*` with a `.*?` to match 'Anvil of Steel'

```
craft\(              #matches 'craft('
(                      #start capturegroup 1
[^ )]*                 #matches everything except space and closing bracket
)                      #ends capturegroup 1
(?:                    #start non capturegroup
                         # space 
(                        #start capturegroup 2
\d+                     #matches character range 0-9 with once or multiple times quantifyer
)                        #ends capturegroup 3
)?                     #ends non capturegroup with once or zero times quantifyer
\)                     #matches ')'
(                      #start capturegroup 3
\d*                    #matches character range 0-9 zero or multiple times
)                      #end capturegroup 3
```
viable input:(with first dice)
`!craft(woodenbow 5)10` => `!1d20+10+5`
`!craft(woodenbow)10` => `!1d20+10+`
`!craft(woodenbow)` => `!1d20++`
`!craft(woodenbow 5)` => `!1d20++5`
only valid with `.*?` instead of `[^ )]*`
`!craft(anvil of steel 5)`

**Comment by OrangeMush28** [comment]
Thank you very much for working out examples. I will take this and play with it to learn what i need to do for my system

Much appreciated

**Comment by SaltatorMortis** [comment]
if you have questions simply ask
with input/output examples..

i found an interesting workaround for a Yes/no way
simply use 01 to calculate the first number
a version with multiple conditions 0,1,2etc 
INSERT the first number in the empty brackets
`[]i[0]{0}{@i[1]{5}{@i[2]{20}{0}}}`
or simple 1 switch
`[]c1;d20+$1*5`

**Comment by obiwankennedy** [comment]
At this time of the day (1:47 am), I'm a bit lazy to read the whole topic, Do you need help ?
