### ISSUE TITLE
Macro with if and division is throwing an error

### ISSUE THREAD

**Issue by swdevlin** [Rolisteam/DiceParser#71]
I am trying to implement Call of Cthulhu's hard skill check. That skill check is roll 1d100 and if it is less than 1/2 the character's skill level then the check is successful. So, if the character has a skill of 70, a hard skill check requires a 1d100 to be 35 or less.

My goal is to have something like `!h70` make a hard skill check, where 70 is the character's non-adjusted skill. What I have at the moment for the macro is:

`!macro h([0-9]+) 1d100i[<\1/2]{"success with $1"}{"fail with $1"} 1`

That macro issues the following error:

`Warning: Unexpected character at 12 - end of command was ignored "]{"success with $1"}{"fail with $1"}"`

For a standard skill check, I am using

`!macro s([0-9]+) 1d100i[<\1]{"success with $1"}{"fail with $1"} 1`

and it works just fine.

Can I do what I want to do?

Thanks.

**Comment by obiwankennedy** [comment]
Arithmetic operation are not supported inside validator.
But you can do the operation first and then compare them.


This command works:
```
!1d100;70/2;$1i[<$2]{"success with $1"}{"fail with $1"}
```



The macro should be:
```
!macro h([0-9]+) 1d100;\1/2;$1i[<$2]{"success with $1"}{"fail with $1"} 1
```

**Comment by swdevlin** [comment]
I knew there had to be a way.

Thanks. And thanks for a great tool.
