### ISSUE TITLE
Macros cannot call RegEx Macro

### ISSUE THREAD

**Issue by maximilianmaihoefner** [Rolisteam/DiceParser#74]
Using the Discord Bot I defined two Macros:
```
!macro ([0-9]+)test \1d100 1
!macro test2 2test 0
```
When calling the first one it works as expected:
```
!3test
# 201
Details:[3d100 (70 90 41)]
```

But when calling the second one there is no Message written to the Channel by the Bot.
When using two simple replace Macro everything works fine:
```
!macro test d100 0
!macro test2 2test 0
```
```
!test2
# 102
Details:[2d100 (13 89)]
```

Am I doing something wrong? Is this intended? Is there a workaround so I can call RegEx Macros from other Macros?

**Comment by obiwankennedy** [comment]
It is depending of the position of the macro inside the macro list. 
Make sure your final macro is at the end of the list, it will be resolved at the end.

**Comment by JoeGans** [comment]
Just for my own sake, as I'll not rem what your comment means ... _correct order_ ...

!macro test2 2test 0
!macro ([0-9]+)test \1d100 1

... tested and works fine ... Thanks, Oki! :)

**Comment by maximilianmaihoefner** [comment]
Thanks! That works perfectly. I expected it to be dependent on order but assumed it was the other way around. It is a little bit counter intuitive that you have to create the Macro which is trying to call another Macro before defining the Macro it is trying to call. Maybe it could be mentioned in the Docs.

It would be nice to have an easy way to rearrange the Macro list, so you don't have to remove a Macro and re-add it. Maybe a Command like `!macro move 3 0` to move the Macro in Position 3 to Position 0. Not sure how hard that would be to implement, but might be nice to have.

**Comment by maximilianmaihoefner** [comment]
I have a follow-up question...
Is it possible to roll dice or do Arithmetics when calling another Macro? Given the following to Macros:
```
!macro test2 test 0
!macro ([0-9]+)test \1d100 1
```
I want to pass another dice role to the test2 Macro like:
```
!1d10test2
or
!(1d10)test2
```
Neither worked for me. I managed to get it working with simple replace Macros, but not with the RegEx Macros.

Is it possible to achieve this somehow? Do I need to escape the dice role/Arithmetics in some special way? Thanks for your help, it's much appreciated.

**Comment by SaltatorMortis** [comment]
the example provided does not call the macro test
your example could be called like this: 
`!1test2`

there are three ways to archive this
way one:
```
!macro (\d+|\d*d\d+)test (\1)d100 1
!macro test d100 0
```


way too:
`!macro (\d+|\d*d\d+)?test [\1];$1c[1..999];$2i:[0]{d100}{(0\1)d100} 1`


way three:
`!macro test d100 0`

the three versions could be called like this: (only with the third you need to provide brackets for the die)
`!test` or `!1test` or `!1d1test` or `!d1test`

if you plan to use the second way you have to use it first in your die stack
DiceParser has only absolute position reference `$1...` and no relative position reference 
`!d100;0;5;1d2te`
`d100;0;5;[1d2];$1c[1..999];$2i:[0]{d100}{(01d2)d100}`
and not
`d100;0;5;[1d2];$4c[1..999];$5i:[0]{d100}{(01d2)d100}`

**Comment by obiwankennedy** [comment]
As it has result to a feature request, I will close this ticket.
