### ISSUE TITLE
[Question] Arithmetic in Output

### ISSUE THREAD

**Issue by VanWarbux** [Rolisteam/DiceParser#76]
Hello,

i wanna roll a d20+6. If the dice roll is 20, i wanna write "CRIT" before writing the dice result.
BUT i still want the dice result plus the flat amount in the output i.e. 26 in this case.

Is that possible?

**Comment by obiwankennedy** [comment]
yes.

> 1d20;$1+6;$1i:[=20]{"CRIT - $2"}{"$2"}

**Comment by VanWarbux** [comment]
Thank you :)

Is it possible to keep the Detalils of the roll...

i.e.  Details:[d8+2  # (6)]

Or do i have to write them myself?

**Comment by obiwankennedy** [comment]
> 1d20;$1+6;$1i:[=20]{"CRIT - $2 Detail: [ @1 ]"}{"$2 - detail: [@1]"}

**Comment by JoeGans** [comment]
Hi Obi 

When I run the command ...

!1d20;$1+6;$1i:[=20]{"CRIT - $2 Detail: [ @1 ]"}{"$2 - detail: [@1]"}

... it shows the following result ... 

15 - detail: [9]

... but I think Van's looking for this too appear ...

**Details:[1d6+2 # (15)]**

... which shows the dice *thrown* from the user? ... Walts

Another, basic, example, without the check produces what he wants ...

WaltsToday at 01:34
!1d6+2
TC Rolls
BOT ... Today at 01:34
# 3
**Details:[1d6+2 (1)]**

**Comment by SaltatorMortis** [comment]
that's impossible without homographs. 
here's a generator https://www.irongeek.com/homoglyph-attack-generator.php
you could add a new line with `\n`, escape `"`
but with the current Build you can't escape dice/position references, thus you need to use a homograph for each letter
ie. `!d12;"\$1;\@1;\%1\""` or `!d12;"\\$1;\\@1;\\%1\""` could parse to `\12;\;\12"`

thus the workaround looks like this;
`!d20;$1+6;$1i:[=20]{"$1,$2 - CRIT"}{"$1,$2"};"\nDetails:[d20;＄1+6;＄1i:[=20]{\"＄2 CRIT\"}{\"＄2 \"}  (@1)]"`

> `16,22 ;`
> `Details:[d20;＄1+6;＄1i:[=20]{"＄2 CRIT"}{"＄2 "}  (16)]`

**Comment by JoeGans** [comment]
Ah, that's surprising ... I would have thought that with a basic command, it outputs what Van was
looking for, so it would have been a simple ref to the original output?  

Guess not! ... Thanks for input!!! :+1: ... Walts
