### ISSUE TITLE
a little error in the colors

### ISSUE THREAD

**Issue by Finch404** [Rolisteam/DiceParser#79]
Hello, Obi.
It’s just a small thing.

![image](https://user-images.githubusercontent.com/40771861/79889552-938cb900-83d4-11ea-8903-e15fa45a3bb6.png)

Have you noticed this blue bracket?
This happens, for example, in commands:

* !d20R[<10]
* !d20e[<15]    (I know it doesn't make much sense)
* !d12r[<3]

The three have this problem, so I think what causes it is the "<".
Kinda insignificant but when I use it in more complex commands, it happens:

![image](https://user-images.githubusercontent.com/40771861/79889643-b4eda500-83d4-11ea-90f8-68ec5ab449d8.png)

* !d20R[<10];$1+6;$1i:[=20]{"CRIT - $2"}{"$2"}

This makes the bot send the message "**CRIT - 26**" if the dice rolls 20, but when it doesn't roll, this is what happens with the colors. I don't know if the "**-**" after **CRIT** is supposed to be colorful too.

Thank you for the attention.

**Comment by obiwankennedy** [comment]
Hello,

I have no way to handle that. 
Discord has a really bad color management. To be honest, they don't have any color management .
To get color, I used a code block with the markdown syntax. So the rest of the role is managed as markdown and I guess < should means some thing in markdown.

**Comment by xehpuk** [comment]
I can inject markdown. That doesn't seem right.

![Markdown injection](https://user-images.githubusercontent.com/3484906/81455115-7d317c00-918e-11ea-9cf8-b64547554827.png)

**Comment by SaltatorMortis** [comment]
ive always thord this was a feature:
try this one to change the display syntax ( in this case markdown to asciidoc)
```
!d10c[<0];"```````asciidoc
= $1 =
NOTE: !d10c[<0] %2
"
```
it returns this:
> ```Markdown
> `
>```
> ```asciidoc
> = 0 =
> NOTE: !d10c[<0] 7
> ```
