### ISSUE TITLE
Possible to have count act on exploeded sums?

### ISSUE THREAD

**Issue by nyclogan** [Rolisteam/DiceParser#81]
Trying to get a house rule working.
Roll xD6, explode 6s and add their values to the 6 that rolled them.
report back the count of summed exploded values equal or greater to the target number.
this allows getting successes on a d6 for a target number greater than 6.
for example, roll 3D6, get 2,4,6. explode the 6 getting a 4, so end results are 2,4,10 with a count >=10 returning a 1 result.
Currently, I can only get it to count individual die, not summed exploded totals. Am I just missing it?

**Comment by nyclogan** [comment]
for clarity, trying to get a count result of 1 onthe following instead of the returned 0:

# 0
Details:[5d6e6sc[>=8] (8 [6,2] 2 1 1 1)]

**Comment by SaltatorMortis** [comment]
the kiss solution is to split the dice and if the sum
!1d6e6i:[>=8]{100};1d6e6i:[>=8]{100};1d6e6i:[>=8]{100};1d6e6i:[>=8]{100};1d6e6i:[>=8]{100}
with 0 or 1 output:
!1d6e6i:[>=8]{1}{0};1d6e6i:[>=8]{1}{0};1d6e6i:[>=8]{1}{0};1d6e6i:[>=8]{1}{0};1d6e6i:[>=8]{1}{0}

**Comment by nyclogan** [comment]
Thanks for the suggestions. I have converted the first one into a repeat command to try and make it easier on players changing the number of die in a roll:
repeat(1d6e6i:[>=8]{"Success %1 "}{"Fail %1"};"@1",2)
but it looks like the repeat command doesn't let each roll display the details. 
I am just getting "Success" or "Fail", if I run the same line without the repeat wrapper I get:
"Sucess 10" or "Fail 3".

**Comment by SaltatorMortis** [comment]
same with the @ or $ ($ even crashes) command 
`!5d6c6;[$1]i:[!=0]{d6e6c[>=2]};$2i:[>=1]{"Success %2"}{"Fail @1"}`


`!macro roll d6c6;[$1]i:[!=0]{d6e6c[>=2]};$2i:[>=1]{"Success %2"}{"Fail @1"} 0`
called:
`!3roll` for 3 dice

**Comment by nyclogan** [comment]
Ok slight modification to your second suggestion looks like it might be working as expected:
!5d6sc6;[$1]i:[!=0]{$1d6s}
this will roll the number of die equal to the number of 6s rolled in the first roll. I think I can work with this. Thank you for your help!

**Comment by SaltatorMortis** [comment]
with  !5d6sc6;[$1]i:[!=0]{$1d6s}
you display a sorted array of dice but do not filter for 8+

**Comment by SaltatorMortis** [comment]
ps if solved close the issue

**Comment by obiwankennedy** [comment]
I just deployed a new version, You can roll:
`!5d6e6sc[?>=8] ` and it will work like you want.

**Comment by nyclogan** [comment]
Great thank you very much. Behaving as desired.
Stay safe.
