### ISSUE TITLE
Discord arithmetic sometimes returns 0 for no reason

### ISSUE THREAD

**Issue by technolapin** [Rolisteam/DiceParser#82]
The ** operator returns randomly 0 or the correct answer on discord.

![](https://image.noelshack.com/fichiers/2020/18/4/1588205813-capture-d-ecran-2020-04-30-02-16-43.png)

**Comment by obiwankennedy** [comment]
Ok that strange.

**Comment by technolapin** [comment]
I have more elements: either everything in the message works, either nothing does.
![](https://image.noelshack.com/fichiers/2020/18/4/1588239831-capture-d-ecran-2020-04-30-11-44-33.png)

**Comment by obiwankennedy** [comment]
Could it be a gitch from discord as ** means bold text in markdown. Perharps Diceparser does not received the proper command ? I will check that.
