### ISSUE TITLE
Alias's seem to delete over time

### ISSUE THREAD

**Issue by iarepandemonium** [Rolisteam/DiceParser#83]
When I was using alias' I set up a lot of them but then after some time they stopped working.

**Comment by obiwankennedy** [comment]
it appears that sometimes the saving into file does not work and then when dicebot is restarted. It lost its alias. So it is recommended to save them into file on your side and be ready to set them again.
I worked to save them into database and it will be deploy soon. Hoping it will fix that.

**Comment by obiwankennedy** [comment]
dupplicate of #33
