### ISSUE TITLE
Macros do not function if they reuse the name of a previously deleted Macro

### ISSUE THREAD

**Issue by SmilingBanditUK** [Rolisteam/DiceParser#84]
Hi, I created some custom dice rolls for various games I run on my Discord server.

These include Dice Rolls to make things earlier for my players in Shadowrun 2e, Hero System 5e and Fate.

I got my Macro's right first time, with Fate and Shadowrun, but I had to put a temporary one in for one of the Hero System rolls while I figured out the logic of how to get it to read the dice and create multiple responses from the same set of dice (for the record, reading "Normal Damage" dice - dice pips are "Stun" damage and "Body" damage is calculated based on each dice rolled: every 1 is 0 Body, every 2-5 is 1 Body, and every 6 is 2 Body.)

The first iteration of the Macro was a simple
"macro d6Normal d6;$1c6;$1c1;$2-$3 #Total Stun ; 6's ; 1's ; Number Added/Subtracted to Calculate Body: 0".  Which when used gave the response: 
**!roll 15d6Normal**
DiceParser: Total Stun ; 6's ; 1's ; Number Added/Subtracted to Calculate Body:
53,2,1,1
Details:[15d6;$1c6;$1c1;$2-$3 # (5 5 4 3 2 2 4 6 2 6 1 3 2 4 4)]

I realised how to get it to do the math needed without showing how many 6's and 1s, and deleted the d6Normal Macro, and rewrote it as:
"macro d6Normal d6;$1c[>0]+$1c[=6]-$1c[=1] #Test 0"
Which should show a comment of "Test",  then show the total pips (Stun), and finally calculate the Body damage as above.  I then ran the test:
**!roll 15d6Normal**
_Nothing happened._

I thought for a moment, checking for typo's and rogue spaces.  Nothing.  So I tried writing the exact same macro under a different name (d6P instead of d6Normal), with no other changes:
"macro d6P d6;$1c[>0]+$1c[=6]-$1c[=1] #Test 0"
And I ran the command:
**!roll 15d6P**
DiceParser: Test
50,16
Details:[15d6;$1c[>0]+$1c[=6]-$1c[=1] # (6 5 2 3 3 5 2 2 2 6 1 5 3 3 2)]

This seems to indicate that it remembers the old Macro names, and they cannot be reused.  How do I get it to allow me to reuse them?  I really need it to be "d6Normal" for my players ease.

**Comment by SmilingBanditUK** [comment]
For reference, my current macro list:
id: 0 Pattern: fate Command: 4d[-1..1] Regexp: False

id: 1 Pattern: OCV Command: +11-(3d6) #Hit DCV: Regexp: False

id: 2 Pattern: ECV Command: +11-(3d6) #Hit ECV: Regexp: False

id: 3 Pattern: .5d6Killing Command: d6+1d3 #Body Damage (Apply Location Modifiers) Regexp: False

id: 4 Pattern: d6+1Killing Command: d6+1 #Body Damage (Apply Location Modifiers) Regexp: False

id: 5 Pattern: d6Effect Command: d6 #Effect Roll: Regexp: False

id: 6 Pattern: d6Killing Command: d6 #Body Damage (Apply Location Modifiers) Regexp: False

id: 7 Pattern: SRd6 Command: d6e6sc[?>=7] #Count Dice That Rollup Regexp: False

id: 8 Pattern: d6P Command: d6;$1c[>0]+$1c[=6]-$1c[=1] #Test Regexp: False

**Comment by SaltatorMortis** [comment]
i don't see any error in the macros.
all macro commands work fine,
the only possible failure point is the macro setting
i mean that you may have accidentally omitted the `0` whilst setting the `d6Normal`
the bot fails requests like this silently

**Comment by SmilingBanditUK** [comment]
Hi, I copied and pasted the command, changing only the name.  If it was wrong for one, it should be wrong for both.

id: 10 Pattern: d6P Command: d6;$1c[>0]+$1c[=6]-$1c[=1] #Test Regexp: False

id: 11 Pattern: d6Normal Command: d6;$1c[>0]+$1c[=6]-$1c[=1] #Test Regexp: False

Both logic are identical, the Regexp: False at the end show that the 0 was included.

This is the response when triggered:
[07:56] SmilingBandit: !roll 5d6P
[07:56] DiceBot: Test
# 14,4
Details:[5d6;$1c[>0]+$1c[=6]-$1c[=1] # (2 4 5 2 1)]
[07:56] SmilingBandit: Roll 5d6Normal
[07:57] SmilingBandit: nothin

**Comment by SmilingBanditUK** [comment]
This is why I am presuming it is the fact I previously had a different Macro saved under that name (d6Normal), as that is the only thing different in the 2 commands.

**Comment by SmilingBanditUK** [comment]
![Command And Macro List](https://user-images.githubusercontent.com/62937093/81533555-5033c380-935e-11ea-89b2-7f1c83a3412b.PNG)

**Comment by SmilingBanditUK** [comment]
As you can see, id's 8 through 11 are the same command, with different names.  And all but id 11 work.  Here is the original d6Normal macro (id 5) : 
![Original d6Normal](https://user-images.githubusercontent.com/62937093/81533898-eff15180-935e-11ea-8f6c-3f17b71972b8.PNG)

**Comment by SaltatorMortis** [comment]
the most important rule in macros is:
macros are executed from top to bottom

iE. in your screen from the 10th the macro 8 gets executed before gets recognised 11
and creates an invalid command
`d6;$1c[>0]+$1c[=6]-$1c[=1]rmal`

another example
with the macros:
- `id0 attack([1-9]+) 1d20-\1#dice-number`
- `id1 Dave 22#Dave stats`

`attackDave`

in text form the first command is the following;
`if the word attack is followed by a number`, roll an d20 and subtract the number from the dice result

but since attackDave is not a number, this is the final result after executing all possible macros
`attack22 `and is therefore not executed
if the dave macro is the first macro executed the command attack22 is true

**Comment by SmilingBanditUK** [comment]
I can see the logic to that, but it failed even when it was the only one on the list using the same command. The only entry was d6Normal.  It didn't work.  I added the others after, to test the logic.

Now it's working even with the others in the list.  I think there was an issue with files somewhere.

Okay to close.

**Comment by SaltatorMortis** [comment]
jup any read write issues would be fixed with the upcoming transfer to an database
