### ISSUE TITLE
New macro refused

### ISSUE THREAD

**Issue by LordMusashi** [Rolisteam/DiceParser#87]
Hi guys,

The bot refuses any new macro on my server, even very simple one (I have tested).

all the running macro are operational 

id: 0 Pattern: sr([0-9]+) Command: \1d6s;$1c[>4];$1c1;\1d1;$3/$4*100i:[>50]{"Nombre de 1 ($3) dépasse 50 % des dés lancés ($4) [@1]"}{"$2 succès [@1]"} Regexp: True

id: 1 Pattern: k([0-9]+)OD([0-9]+) Command: \1d6;$1c[%2=0];$2+\2;$2i:[>=1]{"$2 succès, soit $3 succès avec les OD [@1]"}{"0 succès [@1]"} Regexp: True

id: 2 Pattern: k([0-9]+) Command: \1d6;$1c[%2=0];$2i:[>=1]{"$2 succès [@1]"}{"0 succès [@1]"} Regexp: True

id: 3 Pattern: LK([0-9]+)OD([0-9]+) Command: \1d20;$1c[%2=0];$2+\2;$2i:[>=1]{"$2 succès, soit $3 succès avec les OD [@1]"}{"0 succès [@1]"} Regexp: True

id: 4 Pattern: LK([0-9]+) Command: \1d20;$1c[%2=0];$2i:[>=1]{"$2 succès [@1]"}{"0 succès [@1]"} Regexp: True

id: 5 Pattern: sam([0-9]+)w([0-9]+) Command: \1d12c[>=\2] Regexp: True

id: 6 Pattern: MerX([0-9]+) Command: \1d10e10;$1g10;$1g15;($3*2);$4+$2-$3;"$3 groupes de 15, $2 groupes de 10, entre $4 et $5 mises [@1]" Regexp: True

id: 7 Pattern: Mer([0-9]+) Command: \1d10;$1g10;$1g15;($3*2);$4+$2-$3;"$3 groupes de 15, $2 groupes de 10, entre $4 et $5 mises [@1]" Regexp: True

id: 8 Pattern: merX([0-9]+) Command: \1d10e10g10;"$1 groupe de 10 / $1 mises [@1]" Regexp: True

id: 9 Pattern: mer([0-9]+) Command: \1d10g10;"$1 groupe de 10 / $1 mises [@1]" Regexp: True

id: 10 Pattern: dangerX([0-9]+) Command: \1d10e10g15;"$1 groupe de 15 / $1 mises [@1]" Regexp: True

id: 11 Pattern: danger([0-9]+) Command: \1d10g15;"$1 groupe de 15 / $1 mises [@1]" Regexp: True

but when I want to add a new one :
!macro rdd([0-9]+)/-([0-9]+) 1d100;1-1-\2;\15(10-\2)|10;\1|2;\1|4;$2i:[=-10]{$5}{$7i:[=-9]{$4}{$3}};$62|10;$6|2;100-((100-$6)2|10);100-((100-$6)|10);$1i:[<=$7]{"Réussite particulière [@1] (RN $6 ; RP $7)"}{$1i:[<=$8]{"Réussite significative [@1] (RN $6 ; RS $8)"}{$1i:[<=$6]{"Réussite normale [@1] (RN $6)"}{$1i:[>=$10]{"Echec total [@1] (RN $6 ; ET $10)"}{$1i:[>=$9]{"Echec particulier [@1] (RN $6 ; EP $9)"}{"Echec normal [@1] (RN $6)"}}}}} 1

DiceParser tells me this :
Invalid macro subcommand

Before I did not have any problems, are u aware of some issue or solutions ?

**Comment by doublesupercool** [comment]
I admit I am new to bots and discord, but I just installed this and tried copy and pasting the example macro and got the same result:

Invalid macro subcommand.

For reference I copied and pasted this (from the documentation):

!macro k d10e10k 0

I assume that just adding this as a message would set up the macro.

**Comment by obiwankennedy** [comment]
The syntax has changed. I did not updated the documentation online as now the bot have a better internal documentation for discord bot feature.


`!macro k d10e10k False`

**Comment by doublesupercool** [comment]
Cheers, thanks for that! Works okay now.

**Comment by obiwankennedy** [comment]
probably. It is always a good idea to keep them and be able to reset them.
