### ISSUE TITLE
Unexpected Prefix Behaviours

### ISSUE THREAD

**Issue by SmilingBanditUK** [Rolisteam/DiceParser#89]
Hi, Sorry to ask, but was there any work done on DiceParser in the last 2 weeks?

My Discord instance of DP has developed a frustrating set of behaviours.

1. the prefix reset itself back to ! from !roll
2. once the prefix is re-set back to !roll it is not recognised if there is a space between it and the command, whereas previously it was: for example **!roll 4d6** would result in it rolling 4d6, now it has to be **!roll4d6**

I have tried setting the prefix with a space at the end to "force" the space but it doesn't seem to work:

[06:29] SmilingBanditUK: !2d6
[06:29] BOT DiceBot:
# 11
Details:[2d6 (6 5)]
[06:30] SmilingBanditUK: !prefix set !roll
[06:30] BOT DiceBot: [Prefix]New prefix definition is done!
[06:32] SmilingBanditUK: !roll 2d6
[06:32] SmilingBanditUK: !roll2d6
[06:32] BOT DiceBot:
# 7
Details:[2d6 (1 6)]
[06:37] SmilingBanditUK: !rollprefix set !roll 
[06:37] BOT DiceBot: [Prefix]New prefix definition is done!
[06:37] SmilingBanditUK: !roll 2d6

---

That syntax used to work, when I first had DiceParser on my server:
(from May 20)
[20:55] SmilingBanditUK: !roll 2d6+4 #Kick Ass using Necromancy
[20:55] BOT DiceBot: Kick Ass using Necromancy
# 11
Details:[2d6+4 # (3 4)]

But now it won't recognise the space.

**Comment by obiwankennedy** [comment]
If you want to prefix with a space:
!prefix set "!roll "

**Comment by SmilingBanditUK** [comment]
Including the " "?  I didn't need to do that last time, when I first set it up on the server, I just set it to !roll and it accepted the space (as per the last example above).

I also don't know why it reset to ! in the first place to require it to be redone.

**Comment by JoeGans** [comment]
As far as I'm aware, there's been a few updates so things (I guess?) have been reset?

The command line Obi listed is a straight copy&paste to give the command you want?

Copied from my server... 

Walts Today at 16:51
!prefix set "!roll "

TC Rolls
BOT Today at 16:51
[Prefix]New prefix definition is done!

Walts Today at 16:52
!roll 2d20

TC Rolls
BOT Today at 16:52
Details:[2d20 (20 19)]

-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  
You can play about with it to experiment a bit? ... Walts

**Comment by SmilingBanditUK** [comment]
Thankyou both.  :)  Just wanted to ensure the " were needed :)
