### ISSUE TITLE
Bot not working on one server yet working on others

### ISSUE THREAD

**Issue by Whyzard** [Rolisteam/DiceParser#92]
None of the bot's commands work on my own server, even though they work elsewhere. I have seen the thing with the Twitter bot taking up too much memory, and I suppose it might just be the same issue, but maybe not...

**Comment by Whyzard** [comment]
May I ask why this was closed ? The issue is, as far as I know, still unresolved

**Comment by obiwankennedy** [comment]
This issue occurs in 2 cases:

First, it occurs when the bot is full. For example, the bot may be member of 125000 servers. When it reaches its limit, the bot starts to work strangely and some server can run any commands. To fix I have to increase the capacity and restart the bot. 
I did that 11 days ago. 

secondly, the other case, it is just an issue about permission of the bot, and I can't do anything about it. You have to fix the permission on your server.

As the first case occurs, when you fulfil this ticket, I closed the ticket after increasing the capacity of the bot and restart it.
Anyways, if you are in the second case, I'm powerless.

**Comment by Whyzard** [comment]
I gave it admin permissions. Moreover, it used to work just fine even before that. It still doesn't work on my server

**Comment by obiwankennedy** [comment]
In this case, please go to https://discord.gg/MrMrQwX and contact me by MP  (I'm Obi the admin of this server), then send me an invitation to your server. I will be able to know what is wrong then.
