### ISSUE TITLE
Savage Worlds !1dX;1d6mK1

### ISSUE THREAD

**Issue by ganzuul** [Rolisteam/DiceParser#93]
In Savage Worlds you roll a 'Wild Die' of 1d6 in addition to your skill die and keep the highest. It is also important to keep track of critical failures; if both die come up 1.

In the discord bot !1dX;1d6mK1 does not seem to work, or there is no way of telling which die came up lower. Is there something obvious I am overlooking?

**Comment by obiwankennedy** [comment]
Let's try this command:

```!1d6;1d6;[$1,$2]k1;"Score: $3 - Rolled: [@1, @2]"```

It should be the thing you want.

**Comment by ganzuul** [comment]
Thank you. but it doesn't seem to work with explode-and-keep though. Is there a bug?

**Comment by obiwankennedy** [comment]
I replace K by k. 

> !1d8e8;1d6e6;[$1,$2]k1;$1*$2;$4i:[=1]{"Critical failure [@1,@2]"}{"Score $3 - details [@1,@2]"}

**Comment by ganzuul** [comment]
Oooh!

Thank you! :D

**Comment by obiwankennedy** [comment]
If you need to create a macro in order to type a short text:

# Define macro
```
!macro add ([0-9]+)S "1d\1e\1;1d6e6;[$1,$2]k1;$1*$2;$4i:[=1]{\"Critical failure [@1,@2]\"}{\"Score $3 - details [@1,@2]\"}" True
```


# use it

```
!8S
```
It will run this `!1d8e8;1d6e6;[$1,$2]k1;$1*$2;$4i:[=1]{"Critical failure [@1,@2]"}{"Score $3 - details [@1,@2]"}`

**Comment by Butterfly-Dragon** [comment]
hmmmm... if i write:
```
!1d8e8;1d6e6;[$1,$2]k1;$1*$2;$4i:[=1]{"Critical failure [@1,@2]"}{"Score $3 - details [@1,@2]"}
```
it runs as it should

but if i do
```
!macro add ([0-9]+)S "1d\1e\1;1d6e6;[$1,$2]k1;$1*$2;$4i:[=1]{"Critical failure [@1,@2]"}{"Score $3 - details [@1,@2]"}" True
```
then if i run
```
!8S
```
it returns
```
No valid value at index: $3
```
what did i do wrong?

**Comment by obiwankennedy** [comment]
The macro definition command has changed. It is no longer needed to put the command part inside quote.

```
!macro add ([0-9]+)S "1d\1e\1;1d6e6;[$1,$2]k1;$1*$2;$4i:[=1]{"Critical failure [@1,@2]"}{"Score $3 - details [@1,@2]"}" True
```

![image](https://user-images.githubusercontent.com/69177/149739612-5160f8a5-886f-42f9-9b44-6c71bf263bb4.png)
