### ISSUE TITLE
Character Limit Error

### ISSUE THREAD

**Issue by CryogenicPlanet** [Rolisteam/DiceParser#94]
There should be a check added for character limits so that this kind of bug does not happen to other users,  it should either split of the final message into multiple messages or truncate it and preserve the markdown formatting.

This is a dumb example, where a friend chose a rather large number of dices but nevertheless the visual bug should not show

![image](https://user-images.githubusercontent.com/10355479/85933768-9639ec00-b8f8-11ea-8f42-70874b07bd01.png)

**Comment by obiwankennedy** [comment]
It should be fixed.

**Comment by CryogenicPlanet** [comment]
Yep just tried it, and it send a text file
