### ISSUE TITLE
command "!macro list" don't works

### ISSUE THREAD

**Issue by luizbills** [Rolisteam/DiceParser#98]
In my server the `!macro list` stop working (outputs nothing).

Server ID: 745620797258989589

**Comment by luizbills** [comment]
`!help` and `!alias list` is working.
Also, all macros is working too

**Comment by luizbills** [comment]
I think the output is over the character limit for a single message

**Comment by obiwankennedy** [comment]
You must authorize the bot to send file.
When the limit is reach, diceparser generate a text file and send it.

**Comment by luizbills** [comment]
@obiwankennedy Thanks!
