### ISSUE TITLE
Bot mixing the Macros..

### ISSUE THREAD

**Issue by Ollirg** [Rolisteam/DiceParser#99]
Hello!

I was working on some Alias in my server and I noticed that, for some reason that I don't understand, the Bot has been mixing the results from different Macros...

My Alias is as follows:

id/pattern: uc
Commands:
ga # **O(A) PNJ é um(a)...**
g9;L[e];g9
gb # **..que é..**
gc # **..cuja motivação é...**
gd
ge # **..e que está focado(a) em seu/sua..**

The problem is that, as in the picture below, I have a result from a list in Macro "gd" showing up where the result should be one from a list in macro "gc"
![image](https://user-images.githubusercontent.com/71984698/94372535-f0ec0b00-00d4-11eb-816c-4c74f6dc0263.png)

Is anything wrong in the command, or something like that?

**Comment by obiwankennedy** [comment]
Duplicate - See #142 for explanation
